/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import com.rbkmoney.payouter.domain.enums.CashFlowType;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CashFlowDescription implements Serializable {

    private static final long serialVersionUID = 248232166;

    private Long         id;
    private Long         payoutId;
    private CashFlowType cashFlowType;
    private Integer      count;
    private Long         amount;
    private String       currencyCode;
    private String       description;

    public CashFlowDescription() {}

    public CashFlowDescription(CashFlowDescription value) {
        this.id = value.id;
        this.payoutId = value.payoutId;
        this.cashFlowType = value.cashFlowType;
        this.count = value.count;
        this.amount = value.amount;
        this.currencyCode = value.currencyCode;
        this.description = value.description;
    }

    public CashFlowDescription(
        Long         id,
        Long         payoutId,
        CashFlowType cashFlowType,
        Integer      count,
        Long         amount,
        String       currencyCode,
        String       description
    ) {
        this.id = id;
        this.payoutId = payoutId;
        this.cashFlowType = cashFlowType;
        this.count = count;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.description = description;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPayoutId() {
        return this.payoutId;
    }

    public void setPayoutId(Long payoutId) {
        this.payoutId = payoutId;
    }

    public CashFlowType getCashFlowType() {
        return this.cashFlowType;
    }

    public void setCashFlowType(CashFlowType cashFlowType) {
        this.cashFlowType = cashFlowType;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CashFlowDescription other = (CashFlowDescription) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (payoutId == null) {
            if (other.payoutId != null)
                return false;
        }
        else if (!payoutId.equals(other.payoutId))
            return false;
        if (cashFlowType == null) {
            if (other.cashFlowType != null)
                return false;
        }
        else if (!cashFlowType.equals(other.cashFlowType))
            return false;
        if (count == null) {
            if (other.count != null)
                return false;
        }
        else if (!count.equals(other.count))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!currencyCode.equals(other.currencyCode))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.payoutId == null) ? 0 : this.payoutId.hashCode());
        result = prime * result + ((this.cashFlowType == null) ? 0 : this.cashFlowType.hashCode());
        result = prime * result + ((this.count == null) ? 0 : this.count.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CashFlowDescription (");

        sb.append(id);
        sb.append(", ").append(payoutId);
        sb.append(", ").append(cashFlowType);
        sb.append(", ").append(count);
        sb.append(", ").append(amount);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
