/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventStockMeta implements Serializable {

    private static final long serialVersionUID = -1650324657;

    private Long          lastEventId;
    private LocalDateTime lastEventCreatedAt;

    public EventStockMeta() {}

    public EventStockMeta(EventStockMeta value) {
        this.lastEventId = value.lastEventId;
        this.lastEventCreatedAt = value.lastEventCreatedAt;
    }

    public EventStockMeta(
        Long          lastEventId,
        LocalDateTime lastEventCreatedAt
    ) {
        this.lastEventId = lastEventId;
        this.lastEventCreatedAt = lastEventCreatedAt;
    }

    public Long getLastEventId() {
        return this.lastEventId;
    }

    public void setLastEventId(Long lastEventId) {
        this.lastEventId = lastEventId;
    }

    public LocalDateTime getLastEventCreatedAt() {
        return this.lastEventCreatedAt;
    }

    public void setLastEventCreatedAt(LocalDateTime lastEventCreatedAt) {
        this.lastEventCreatedAt = lastEventCreatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EventStockMeta other = (EventStockMeta) obj;
        if (lastEventId == null) {
            if (other.lastEventId != null)
                return false;
        }
        else if (!lastEventId.equals(other.lastEventId))
            return false;
        if (lastEventCreatedAt == null) {
            if (other.lastEventCreatedAt != null)
                return false;
        }
        else if (!lastEventCreatedAt.equals(other.lastEventCreatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.lastEventId == null) ? 0 : this.lastEventId.hashCode());
        result = prime * result + ((this.lastEventCreatedAt == null) ? 0 : this.lastEventCreatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventStockMeta (");

        sb.append(lastEventId);
        sb.append(", ").append(lastEventCreatedAt);

        sb.append(")");
        return sb.toString();
    }
}
