/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoice implements Serializable {

    private static final long serialVersionUID = 18831897;

    private String        id;
    private String        partyId;
    private String        shopId;
    private String        contractId;
    private LocalDateTime createdAt;
    private Long          partyRevision;

    public Invoice() {}

    public Invoice(Invoice value) {
        this.id = value.id;
        this.partyId = value.partyId;
        this.shopId = value.shopId;
        this.contractId = value.contractId;
        this.createdAt = value.createdAt;
        this.partyRevision = value.partyRevision;
    }

    public Invoice(
        String        id,
        String        partyId,
        String        shopId,
        String        contractId,
        LocalDateTime createdAt,
        Long          partyRevision
    ) {
        this.id = id;
        this.partyId = partyId;
        this.shopId = shopId;
        this.contractId = contractId;
        this.createdAt = createdAt;
        this.partyRevision = partyRevision;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public Long getPartyRevision() {
        return this.partyRevision;
    }

    public void setPartyRevision(Long partyRevision) {
        this.partyRevision = partyRevision;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Invoice other = (Invoice) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (partyRevision == null) {
            if (other.partyRevision != null)
                return false;
        }
        else if (!partyRevision.equals(other.partyRevision))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.partyRevision == null) ? 0 : this.partyRevision.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Invoice (");

        sb.append(id);
        sb.append(", ").append(partyId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(partyRevision);

        sb.append(")");
        return sb.toString();
    }
}
