/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobMeta implements Serializable {

    private static final long serialVersionUID = 1264346689;

    private String        partyId;
    private String        contractId;
    private String        payoutToolId;
    private Integer       calendarId;
    private Integer       schedulerId;
    private LocalDateTime wtime;

    public JobMeta() {}

    public JobMeta(JobMeta value) {
        this.partyId = value.partyId;
        this.contractId = value.contractId;
        this.payoutToolId = value.payoutToolId;
        this.calendarId = value.calendarId;
        this.schedulerId = value.schedulerId;
        this.wtime = value.wtime;
    }

    public JobMeta(
        String        partyId,
        String        contractId,
        String        payoutToolId,
        Integer       calendarId,
        Integer       schedulerId,
        LocalDateTime wtime
    ) {
        this.partyId = partyId;
        this.contractId = contractId;
        this.payoutToolId = payoutToolId;
        this.calendarId = calendarId;
        this.schedulerId = schedulerId;
        this.wtime = wtime;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getContractId() {
        return this.contractId;
    }

    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    public String getPayoutToolId() {
        return this.payoutToolId;
    }

    public void setPayoutToolId(String payoutToolId) {
        this.payoutToolId = payoutToolId;
    }

    public Integer getCalendarId() {
        return this.calendarId;
    }

    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }

    public Integer getSchedulerId() {
        return this.schedulerId;
    }

    public void setSchedulerId(Integer schedulerId) {
        this.schedulerId = schedulerId;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JobMeta other = (JobMeta) obj;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (contractId == null) {
            if (other.contractId != null)
                return false;
        }
        else if (!contractId.equals(other.contractId))
            return false;
        if (payoutToolId == null) {
            if (other.payoutToolId != null)
                return false;
        }
        else if (!payoutToolId.equals(other.payoutToolId))
            return false;
        if (calendarId == null) {
            if (other.calendarId != null)
                return false;
        }
        else if (!calendarId.equals(other.calendarId))
            return false;
        if (schedulerId == null) {
            if (other.schedulerId != null)
                return false;
        }
        else if (!schedulerId.equals(other.schedulerId))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.contractId == null) ? 0 : this.contractId.hashCode());
        result = prime * result + ((this.payoutToolId == null) ? 0 : this.payoutToolId.hashCode());
        result = prime * result + ((this.calendarId == null) ? 0 : this.calendarId.hashCode());
        result = prime * result + ((this.schedulerId == null) ? 0 : this.schedulerId.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobMeta (");

        sb.append(partyId);
        sb.append(", ").append(contractId);
        sb.append(", ").append(payoutToolId);
        sb.append(", ").append(calendarId);
        sb.append(", ").append(schedulerId);
        sb.append(", ").append(wtime);

        sb.append(")");
        return sb.toString();
    }
}
