/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import com.rbkmoney.payouter.domain.enums.PaymentStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payment implements Serializable {

    private static final long serialVersionUID = -1523659690;

    private Long          id;
    private Long          eventId;
    private String        invoiceId;
    private String        paymentId;
    private String        partyId;
    private String        shopId;
    private Integer       providerId;
    private PaymentStatus status;
    private Long          payoutId;
    private Long          amount;
    private Long          providerFee;
    private Long          fee;
    private Long          externalFee;
    private String        currencyCode;
    private LocalDateTime capturedAt;
    private Boolean       test;
    private LocalDateTime createdAt;
    private Long          guaranteeDeposit;
    private Integer       terminalId;
    private Long          domainRevision;

    public Payment() {}

    public Payment(Payment value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.invoiceId = value.invoiceId;
        this.paymentId = value.paymentId;
        this.partyId = value.partyId;
        this.shopId = value.shopId;
        this.providerId = value.providerId;
        this.status = value.status;
        this.payoutId = value.payoutId;
        this.amount = value.amount;
        this.providerFee = value.providerFee;
        this.fee = value.fee;
        this.externalFee = value.externalFee;
        this.currencyCode = value.currencyCode;
        this.capturedAt = value.capturedAt;
        this.test = value.test;
        this.createdAt = value.createdAt;
        this.guaranteeDeposit = value.guaranteeDeposit;
        this.terminalId = value.terminalId;
        this.domainRevision = value.domainRevision;
    }

    public Payment(
        Long          id,
        Long          eventId,
        String        invoiceId,
        String        paymentId,
        String        partyId,
        String        shopId,
        Integer       providerId,
        PaymentStatus status,
        Long          payoutId,
        Long          amount,
        Long          providerFee,
        Long          fee,
        Long          externalFee,
        String        currencyCode,
        LocalDateTime capturedAt,
        Boolean       test,
        LocalDateTime createdAt,
        Long          guaranteeDeposit,
        Integer       terminalId,
        Long          domainRevision
    ) {
        this.id = id;
        this.eventId = eventId;
        this.invoiceId = invoiceId;
        this.paymentId = paymentId;
        this.partyId = partyId;
        this.shopId = shopId;
        this.providerId = providerId;
        this.status = status;
        this.payoutId = payoutId;
        this.amount = amount;
        this.providerFee = providerFee;
        this.fee = fee;
        this.externalFee = externalFee;
        this.currencyCode = currencyCode;
        this.capturedAt = capturedAt;
        this.test = test;
        this.createdAt = createdAt;
        this.guaranteeDeposit = guaranteeDeposit;
        this.terminalId = terminalId;
        this.domainRevision = domainRevision;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getInvoiceId() {
        return this.invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public Integer getProviderId() {
        return this.providerId;
    }

    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    public PaymentStatus getStatus() {
        return this.status;
    }

    public void setStatus(PaymentStatus status) {
        this.status = status;
    }

    public Long getPayoutId() {
        return this.payoutId;
    }

    public void setPayoutId(Long payoutId) {
        this.payoutId = payoutId;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getProviderFee() {
        return this.providerFee;
    }

    public void setProviderFee(Long providerFee) {
        this.providerFee = providerFee;
    }

    public Long getFee() {
        return this.fee;
    }

    public void setFee(Long fee) {
        this.fee = fee;
    }

    public Long getExternalFee() {
        return this.externalFee;
    }

    public void setExternalFee(Long externalFee) {
        this.externalFee = externalFee;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public LocalDateTime getCapturedAt() {
        return this.capturedAt;
    }

    public void setCapturedAt(LocalDateTime capturedAt) {
        this.capturedAt = capturedAt;
    }

    public Boolean getTest() {
        return this.test;
    }

    public void setTest(Boolean test) {
        this.test = test;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public Long getGuaranteeDeposit() {
        return this.guaranteeDeposit;
    }

    public void setGuaranteeDeposit(Long guaranteeDeposit) {
        this.guaranteeDeposit = guaranteeDeposit;
    }

    public Integer getTerminalId() {
        return this.terminalId;
    }

    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    public Long getDomainRevision() {
        return this.domainRevision;
    }

    public void setDomainRevision(Long domainRevision) {
        this.domainRevision = domainRevision;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Payment other = (Payment) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (invoiceId == null) {
            if (other.invoiceId != null)
                return false;
        }
        else if (!invoiceId.equals(other.invoiceId))
            return false;
        if (paymentId == null) {
            if (other.paymentId != null)
                return false;
        }
        else if (!paymentId.equals(other.paymentId))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (providerId == null) {
            if (other.providerId != null)
                return false;
        }
        else if (!providerId.equals(other.providerId))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (payoutId == null) {
            if (other.payoutId != null)
                return false;
        }
        else if (!payoutId.equals(other.payoutId))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (providerFee == null) {
            if (other.providerFee != null)
                return false;
        }
        else if (!providerFee.equals(other.providerFee))
            return false;
        if (fee == null) {
            if (other.fee != null)
                return false;
        }
        else if (!fee.equals(other.fee))
            return false;
        if (externalFee == null) {
            if (other.externalFee != null)
                return false;
        }
        else if (!externalFee.equals(other.externalFee))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!currencyCode.equals(other.currencyCode))
            return false;
        if (capturedAt == null) {
            if (other.capturedAt != null)
                return false;
        }
        else if (!capturedAt.equals(other.capturedAt))
            return false;
        if (test == null) {
            if (other.test != null)
                return false;
        }
        else if (!test.equals(other.test))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (guaranteeDeposit == null) {
            if (other.guaranteeDeposit != null)
                return false;
        }
        else if (!guaranteeDeposit.equals(other.guaranteeDeposit))
            return false;
        if (terminalId == null) {
            if (other.terminalId != null)
                return false;
        }
        else if (!terminalId.equals(other.terminalId))
            return false;
        if (domainRevision == null) {
            if (other.domainRevision != null)
                return false;
        }
        else if (!domainRevision.equals(other.domainRevision))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.invoiceId == null) ? 0 : this.invoiceId.hashCode());
        result = prime * result + ((this.paymentId == null) ? 0 : this.paymentId.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.providerId == null) ? 0 : this.providerId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.payoutId == null) ? 0 : this.payoutId.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.providerFee == null) ? 0 : this.providerFee.hashCode());
        result = prime * result + ((this.fee == null) ? 0 : this.fee.hashCode());
        result = prime * result + ((this.externalFee == null) ? 0 : this.externalFee.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        result = prime * result + ((this.capturedAt == null) ? 0 : this.capturedAt.hashCode());
        result = prime * result + ((this.test == null) ? 0 : this.test.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.guaranteeDeposit == null) ? 0 : this.guaranteeDeposit.hashCode());
        result = prime * result + ((this.terminalId == null) ? 0 : this.terminalId.hashCode());
        result = prime * result + ((this.domainRevision == null) ? 0 : this.domainRevision.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payment (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(invoiceId);
        sb.append(", ").append(paymentId);
        sb.append(", ").append(partyId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(providerId);
        sb.append(", ").append(status);
        sb.append(", ").append(payoutId);
        sb.append(", ").append(amount);
        sb.append(", ").append(providerFee);
        sb.append(", ").append(fee);
        sb.append(", ").append(externalFee);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(capturedAt);
        sb.append(", ").append(test);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(guaranteeDeposit);
        sb.append(", ").append(terminalId);
        sb.append(", ").append(domainRevision);

        sb.append(")");
        return sb.toString();
    }
}
