/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import com.rbkmoney.payouter.domain.enums.PayoutStatus;
import com.rbkmoney.payouter.domain.enums.PayoutType;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payout implements Serializable {

    private static final long serialVersionUID = -753068619;

    private Long          id;
    private String        partyId;
    private String        shopId;
    private LocalDateTime createdAt;
    private LocalDateTime fromTime;
    private LocalDateTime toTime;
    private PayoutStatus  status;
    private PayoutType    payoutType;
    private Long          amount;
    private Long          shopAcc;
    private Long          shopPayoutAcc;
    private String        currencyCode;
    private String        bankAccount;
    private String        corAccount;
    private String        bankBik;
    private String        bankName;
    private String        bankPostAccount;
    private String        inn;
    private String        purpose;
    private String        description;
    private String        accountLegalAgreementId;
    private LocalDateTime accountLegalAgreementSignedAt;

    public Payout() {}

    public Payout(Payout value) {
        this.id = value.id;
        this.partyId = value.partyId;
        this.shopId = value.shopId;
        this.createdAt = value.createdAt;
        this.fromTime = value.fromTime;
        this.toTime = value.toTime;
        this.status = value.status;
        this.payoutType = value.payoutType;
        this.amount = value.amount;
        this.shopAcc = value.shopAcc;
        this.shopPayoutAcc = value.shopPayoutAcc;
        this.currencyCode = value.currencyCode;
        this.bankAccount = value.bankAccount;
        this.corAccount = value.corAccount;
        this.bankBik = value.bankBik;
        this.bankName = value.bankName;
        this.bankPostAccount = value.bankPostAccount;
        this.inn = value.inn;
        this.purpose = value.purpose;
        this.description = value.description;
        this.accountLegalAgreementId = value.accountLegalAgreementId;
        this.accountLegalAgreementSignedAt = value.accountLegalAgreementSignedAt;
    }

    public Payout(
        Long          id,
        String        partyId,
        String        shopId,
        LocalDateTime createdAt,
        LocalDateTime fromTime,
        LocalDateTime toTime,
        PayoutStatus  status,
        PayoutType    payoutType,
        Long          amount,
        Long          shopAcc,
        Long          shopPayoutAcc,
        String        currencyCode,
        String        bankAccount,
        String        corAccount,
        String        bankBik,
        String        bankName,
        String        bankPostAccount,
        String        inn,
        String        purpose,
        String        description,
        String        accountLegalAgreementId,
        LocalDateTime accountLegalAgreementSignedAt
    ) {
        this.id = id;
        this.partyId = partyId;
        this.shopId = shopId;
        this.createdAt = createdAt;
        this.fromTime = fromTime;
        this.toTime = toTime;
        this.status = status;
        this.payoutType = payoutType;
        this.amount = amount;
        this.shopAcc = shopAcc;
        this.shopPayoutAcc = shopPayoutAcc;
        this.currencyCode = currencyCode;
        this.bankAccount = bankAccount;
        this.corAccount = corAccount;
        this.bankBik = bankBik;
        this.bankName = bankName;
        this.bankPostAccount = bankPostAccount;
        this.inn = inn;
        this.purpose = purpose;
        this.description = description;
        this.accountLegalAgreementId = accountLegalAgreementId;
        this.accountLegalAgreementSignedAt = accountLegalAgreementSignedAt;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getFromTime() {
        return this.fromTime;
    }

    public void setFromTime(LocalDateTime fromTime) {
        this.fromTime = fromTime;
    }

    public LocalDateTime getToTime() {
        return this.toTime;
    }

    public void setToTime(LocalDateTime toTime) {
        this.toTime = toTime;
    }

    public PayoutStatus getStatus() {
        return this.status;
    }

    public void setStatus(PayoutStatus status) {
        this.status = status;
    }

    public PayoutType getPayoutType() {
        return this.payoutType;
    }

    public void setPayoutType(PayoutType payoutType) {
        this.payoutType = payoutType;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getShopAcc() {
        return this.shopAcc;
    }

    public void setShopAcc(Long shopAcc) {
        this.shopAcc = shopAcc;
    }

    public Long getShopPayoutAcc() {
        return this.shopPayoutAcc;
    }

    public void setShopPayoutAcc(Long shopPayoutAcc) {
        this.shopPayoutAcc = shopPayoutAcc;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getBankAccount() {
        return this.bankAccount;
    }

    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    public String getCorAccount() {
        return this.corAccount;
    }

    public void setCorAccount(String corAccount) {
        this.corAccount = corAccount;
    }

    public String getBankBik() {
        return this.bankBik;
    }

    public void setBankBik(String bankBik) {
        this.bankBik = bankBik;
    }

    public String getBankName() {
        return this.bankName;
    }

    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankPostAccount() {
        return this.bankPostAccount;
    }

    public void setBankPostAccount(String bankPostAccount) {
        this.bankPostAccount = bankPostAccount;
    }

    public String getInn() {
        return this.inn;
    }

    public void setInn(String inn) {
        this.inn = inn;
    }

    public String getPurpose() {
        return this.purpose;
    }

    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAccountLegalAgreementId() {
        return this.accountLegalAgreementId;
    }

    public void setAccountLegalAgreementId(String accountLegalAgreementId) {
        this.accountLegalAgreementId = accountLegalAgreementId;
    }

    public LocalDateTime getAccountLegalAgreementSignedAt() {
        return this.accountLegalAgreementSignedAt;
    }

    public void setAccountLegalAgreementSignedAt(LocalDateTime accountLegalAgreementSignedAt) {
        this.accountLegalAgreementSignedAt = accountLegalAgreementSignedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Payout other = (Payout) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (fromTime == null) {
            if (other.fromTime != null)
                return false;
        }
        else if (!fromTime.equals(other.fromTime))
            return false;
        if (toTime == null) {
            if (other.toTime != null)
                return false;
        }
        else if (!toTime.equals(other.toTime))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (payoutType == null) {
            if (other.payoutType != null)
                return false;
        }
        else if (!payoutType.equals(other.payoutType))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (shopAcc == null) {
            if (other.shopAcc != null)
                return false;
        }
        else if (!shopAcc.equals(other.shopAcc))
            return false;
        if (shopPayoutAcc == null) {
            if (other.shopPayoutAcc != null)
                return false;
        }
        else if (!shopPayoutAcc.equals(other.shopPayoutAcc))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!currencyCode.equals(other.currencyCode))
            return false;
        if (bankAccount == null) {
            if (other.bankAccount != null)
                return false;
        }
        else if (!bankAccount.equals(other.bankAccount))
            return false;
        if (corAccount == null) {
            if (other.corAccount != null)
                return false;
        }
        else if (!corAccount.equals(other.corAccount))
            return false;
        if (bankBik == null) {
            if (other.bankBik != null)
                return false;
        }
        else if (!bankBik.equals(other.bankBik))
            return false;
        if (bankName == null) {
            if (other.bankName != null)
                return false;
        }
        else if (!bankName.equals(other.bankName))
            return false;
        if (bankPostAccount == null) {
            if (other.bankPostAccount != null)
                return false;
        }
        else if (!bankPostAccount.equals(other.bankPostAccount))
            return false;
        if (inn == null) {
            if (other.inn != null)
                return false;
        }
        else if (!inn.equals(other.inn))
            return false;
        if (purpose == null) {
            if (other.purpose != null)
                return false;
        }
        else if (!purpose.equals(other.purpose))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (accountLegalAgreementId == null) {
            if (other.accountLegalAgreementId != null)
                return false;
        }
        else if (!accountLegalAgreementId.equals(other.accountLegalAgreementId))
            return false;
        if (accountLegalAgreementSignedAt == null) {
            if (other.accountLegalAgreementSignedAt != null)
                return false;
        }
        else if (!accountLegalAgreementSignedAt.equals(other.accountLegalAgreementSignedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.fromTime == null) ? 0 : this.fromTime.hashCode());
        result = prime * result + ((this.toTime == null) ? 0 : this.toTime.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.payoutType == null) ? 0 : this.payoutType.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.shopAcc == null) ? 0 : this.shopAcc.hashCode());
        result = prime * result + ((this.shopPayoutAcc == null) ? 0 : this.shopPayoutAcc.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        result = prime * result + ((this.bankAccount == null) ? 0 : this.bankAccount.hashCode());
        result = prime * result + ((this.corAccount == null) ? 0 : this.corAccount.hashCode());
        result = prime * result + ((this.bankBik == null) ? 0 : this.bankBik.hashCode());
        result = prime * result + ((this.bankName == null) ? 0 : this.bankName.hashCode());
        result = prime * result + ((this.bankPostAccount == null) ? 0 : this.bankPostAccount.hashCode());
        result = prime * result + ((this.inn == null) ? 0 : this.inn.hashCode());
        result = prime * result + ((this.purpose == null) ? 0 : this.purpose.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.accountLegalAgreementId == null) ? 0 : this.accountLegalAgreementId.hashCode());
        result = prime * result + ((this.accountLegalAgreementSignedAt == null) ? 0 : this.accountLegalAgreementSignedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Payout (");

        sb.append(id);
        sb.append(", ").append(partyId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(fromTime);
        sb.append(", ").append(toTime);
        sb.append(", ").append(status);
        sb.append(", ").append(payoutType);
        sb.append(", ").append(amount);
        sb.append(", ").append(shopAcc);
        sb.append(", ").append(shopPayoutAcc);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(bankAccount);
        sb.append(", ").append(corAccount);
        sb.append(", ").append(bankBik);
        sb.append(", ").append(bankName);
        sb.append(", ").append(bankPostAccount);
        sb.append(", ").append(inn);
        sb.append(", ").append(purpose);
        sb.append(", ").append(description);
        sb.append(", ").append(accountLegalAgreementId);
        sb.append(", ").append(accountLegalAgreementSignedAt);

        sb.append(")");
        return sb.toString();
    }
}
