/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayoutEvent implements Serializable {

    private static final long serialVersionUID = -656701824;

    private Long          eventId;
    private LocalDateTime eventCreatedAt;
    private String        eventType;
    private String        payoutId;
    private String        payoutPartyId;
    private String        payoutShopId;
    private LocalDateTime payoutCreatedAt;
    private String        payoutStatus;
    private String        payoutStatusCancelDetails;
    private String        payoutType;
    private String        payoutCashFlow;
    private String        payoutPaidDetailsType;
    private String        payoutCardToken;
    private String        payoutCardPaymentSystem;
    private String        payoutCardBin;
    private String        payoutCardMaskedPan;
    private String        payoutCardProviderName;
    private String        payoutCardProviderTransactionId;
    private String        payoutAccountId;
    private String        payoutAccountBankName;
    private String        payoutAccountBankPostId;
    private String        payoutAccountBankLocalCode;
    private String        payoutAccountInn;
    private String        payoutAccountPurpose;
    private String        payoutAccountLegalAgreementId;
    private LocalDateTime payoutAccountLegalAgreementSignedAt;
    private String        userId;
    private String        userType;
    private String        payoutAccountType;
    private String        payoutAccountBankAddress;
    private String        payoutAccountBankBic;
    private String        payoutAccountBankIban;
    private String        payoutAccountLegalName;
    private String        payoutAccountTradingName;
    private String        payoutAccountRegisteredAddress;
    private String        payoutAccountActualAddress;
    private String        payoutAccountRegisteredNumber;

    public PayoutEvent() {}

    public PayoutEvent(PayoutEvent value) {
        this.eventId = value.eventId;
        this.eventCreatedAt = value.eventCreatedAt;
        this.eventType = value.eventType;
        this.payoutId = value.payoutId;
        this.payoutPartyId = value.payoutPartyId;
        this.payoutShopId = value.payoutShopId;
        this.payoutCreatedAt = value.payoutCreatedAt;
        this.payoutStatus = value.payoutStatus;
        this.payoutStatusCancelDetails = value.payoutStatusCancelDetails;
        this.payoutType = value.payoutType;
        this.payoutCashFlow = value.payoutCashFlow;
        this.payoutPaidDetailsType = value.payoutPaidDetailsType;
        this.payoutCardToken = value.payoutCardToken;
        this.payoutCardPaymentSystem = value.payoutCardPaymentSystem;
        this.payoutCardBin = value.payoutCardBin;
        this.payoutCardMaskedPan = value.payoutCardMaskedPan;
        this.payoutCardProviderName = value.payoutCardProviderName;
        this.payoutCardProviderTransactionId = value.payoutCardProviderTransactionId;
        this.payoutAccountId = value.payoutAccountId;
        this.payoutAccountBankName = value.payoutAccountBankName;
        this.payoutAccountBankPostId = value.payoutAccountBankPostId;
        this.payoutAccountBankLocalCode = value.payoutAccountBankLocalCode;
        this.payoutAccountInn = value.payoutAccountInn;
        this.payoutAccountPurpose = value.payoutAccountPurpose;
        this.payoutAccountLegalAgreementId = value.payoutAccountLegalAgreementId;
        this.payoutAccountLegalAgreementSignedAt = value.payoutAccountLegalAgreementSignedAt;
        this.userId = value.userId;
        this.userType = value.userType;
        this.payoutAccountType = value.payoutAccountType;
        this.payoutAccountBankAddress = value.payoutAccountBankAddress;
        this.payoutAccountBankBic = value.payoutAccountBankBic;
        this.payoutAccountBankIban = value.payoutAccountBankIban;
        this.payoutAccountLegalName = value.payoutAccountLegalName;
        this.payoutAccountTradingName = value.payoutAccountTradingName;
        this.payoutAccountRegisteredAddress = value.payoutAccountRegisteredAddress;
        this.payoutAccountActualAddress = value.payoutAccountActualAddress;
        this.payoutAccountRegisteredNumber = value.payoutAccountRegisteredNumber;
    }

    public PayoutEvent(
        Long          eventId,
        LocalDateTime eventCreatedAt,
        String        eventType,
        String        payoutId,
        String        payoutPartyId,
        String        payoutShopId,
        LocalDateTime payoutCreatedAt,
        String        payoutStatus,
        String        payoutStatusCancelDetails,
        String        payoutType,
        String        payoutCashFlow,
        String        payoutPaidDetailsType,
        String        payoutCardToken,
        String        payoutCardPaymentSystem,
        String        payoutCardBin,
        String        payoutCardMaskedPan,
        String        payoutCardProviderName,
        String        payoutCardProviderTransactionId,
        String        payoutAccountId,
        String        payoutAccountBankName,
        String        payoutAccountBankPostId,
        String        payoutAccountBankLocalCode,
        String        payoutAccountInn,
        String        payoutAccountPurpose,
        String        payoutAccountLegalAgreementId,
        LocalDateTime payoutAccountLegalAgreementSignedAt,
        String        userId,
        String        userType,
        String        payoutAccountType,
        String        payoutAccountBankAddress,
        String        payoutAccountBankBic,
        String        payoutAccountBankIban,
        String        payoutAccountLegalName,
        String        payoutAccountTradingName,
        String        payoutAccountRegisteredAddress,
        String        payoutAccountActualAddress,
        String        payoutAccountRegisteredNumber
    ) {
        this.eventId = eventId;
        this.eventCreatedAt = eventCreatedAt;
        this.eventType = eventType;
        this.payoutId = payoutId;
        this.payoutPartyId = payoutPartyId;
        this.payoutShopId = payoutShopId;
        this.payoutCreatedAt = payoutCreatedAt;
        this.payoutStatus = payoutStatus;
        this.payoutStatusCancelDetails = payoutStatusCancelDetails;
        this.payoutType = payoutType;
        this.payoutCashFlow = payoutCashFlow;
        this.payoutPaidDetailsType = payoutPaidDetailsType;
        this.payoutCardToken = payoutCardToken;
        this.payoutCardPaymentSystem = payoutCardPaymentSystem;
        this.payoutCardBin = payoutCardBin;
        this.payoutCardMaskedPan = payoutCardMaskedPan;
        this.payoutCardProviderName = payoutCardProviderName;
        this.payoutCardProviderTransactionId = payoutCardProviderTransactionId;
        this.payoutAccountId = payoutAccountId;
        this.payoutAccountBankName = payoutAccountBankName;
        this.payoutAccountBankPostId = payoutAccountBankPostId;
        this.payoutAccountBankLocalCode = payoutAccountBankLocalCode;
        this.payoutAccountInn = payoutAccountInn;
        this.payoutAccountPurpose = payoutAccountPurpose;
        this.payoutAccountLegalAgreementId = payoutAccountLegalAgreementId;
        this.payoutAccountLegalAgreementSignedAt = payoutAccountLegalAgreementSignedAt;
        this.userId = userId;
        this.userType = userType;
        this.payoutAccountType = payoutAccountType;
        this.payoutAccountBankAddress = payoutAccountBankAddress;
        this.payoutAccountBankBic = payoutAccountBankBic;
        this.payoutAccountBankIban = payoutAccountBankIban;
        this.payoutAccountLegalName = payoutAccountLegalName;
        this.payoutAccountTradingName = payoutAccountTradingName;
        this.payoutAccountRegisteredAddress = payoutAccountRegisteredAddress;
        this.payoutAccountActualAddress = payoutAccountActualAddress;
        this.payoutAccountRegisteredNumber = payoutAccountRegisteredNumber;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public LocalDateTime getEventCreatedAt() {
        return this.eventCreatedAt;
    }

    public void setEventCreatedAt(LocalDateTime eventCreatedAt) {
        this.eventCreatedAt = eventCreatedAt;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getPayoutId() {
        return this.payoutId;
    }

    public void setPayoutId(String payoutId) {
        this.payoutId = payoutId;
    }

    public String getPayoutPartyId() {
        return this.payoutPartyId;
    }

    public void setPayoutPartyId(String payoutPartyId) {
        this.payoutPartyId = payoutPartyId;
    }

    public String getPayoutShopId() {
        return this.payoutShopId;
    }

    public void setPayoutShopId(String payoutShopId) {
        this.payoutShopId = payoutShopId;
    }

    public LocalDateTime getPayoutCreatedAt() {
        return this.payoutCreatedAt;
    }

    public void setPayoutCreatedAt(LocalDateTime payoutCreatedAt) {
        this.payoutCreatedAt = payoutCreatedAt;
    }

    public String getPayoutStatus() {
        return this.payoutStatus;
    }

    public void setPayoutStatus(String payoutStatus) {
        this.payoutStatus = payoutStatus;
    }

    public String getPayoutStatusCancelDetails() {
        return this.payoutStatusCancelDetails;
    }

    public void setPayoutStatusCancelDetails(String payoutStatusCancelDetails) {
        this.payoutStatusCancelDetails = payoutStatusCancelDetails;
    }

    public String getPayoutType() {
        return this.payoutType;
    }

    public void setPayoutType(String payoutType) {
        this.payoutType = payoutType;
    }

    public String getPayoutCashFlow() {
        return this.payoutCashFlow;
    }

    public void setPayoutCashFlow(String payoutCashFlow) {
        this.payoutCashFlow = payoutCashFlow;
    }

    public String getPayoutPaidDetailsType() {
        return this.payoutPaidDetailsType;
    }

    public void setPayoutPaidDetailsType(String payoutPaidDetailsType) {
        this.payoutPaidDetailsType = payoutPaidDetailsType;
    }

    public String getPayoutCardToken() {
        return this.payoutCardToken;
    }

    public void setPayoutCardToken(String payoutCardToken) {
        this.payoutCardToken = payoutCardToken;
    }

    public String getPayoutCardPaymentSystem() {
        return this.payoutCardPaymentSystem;
    }

    public void setPayoutCardPaymentSystem(String payoutCardPaymentSystem) {
        this.payoutCardPaymentSystem = payoutCardPaymentSystem;
    }

    public String getPayoutCardBin() {
        return this.payoutCardBin;
    }

    public void setPayoutCardBin(String payoutCardBin) {
        this.payoutCardBin = payoutCardBin;
    }

    public String getPayoutCardMaskedPan() {
        return this.payoutCardMaskedPan;
    }

    public void setPayoutCardMaskedPan(String payoutCardMaskedPan) {
        this.payoutCardMaskedPan = payoutCardMaskedPan;
    }

    public String getPayoutCardProviderName() {
        return this.payoutCardProviderName;
    }

    public void setPayoutCardProviderName(String payoutCardProviderName) {
        this.payoutCardProviderName = payoutCardProviderName;
    }

    public String getPayoutCardProviderTransactionId() {
        return this.payoutCardProviderTransactionId;
    }

    public void setPayoutCardProviderTransactionId(String payoutCardProviderTransactionId) {
        this.payoutCardProviderTransactionId = payoutCardProviderTransactionId;
    }

    public String getPayoutAccountId() {
        return this.payoutAccountId;
    }

    public void setPayoutAccountId(String payoutAccountId) {
        this.payoutAccountId = payoutAccountId;
    }

    public String getPayoutAccountBankName() {
        return this.payoutAccountBankName;
    }

    public void setPayoutAccountBankName(String payoutAccountBankName) {
        this.payoutAccountBankName = payoutAccountBankName;
    }

    public String getPayoutAccountBankPostId() {
        return this.payoutAccountBankPostId;
    }

    public void setPayoutAccountBankPostId(String payoutAccountBankPostId) {
        this.payoutAccountBankPostId = payoutAccountBankPostId;
    }

    public String getPayoutAccountBankLocalCode() {
        return this.payoutAccountBankLocalCode;
    }

    public void setPayoutAccountBankLocalCode(String payoutAccountBankLocalCode) {
        this.payoutAccountBankLocalCode = payoutAccountBankLocalCode;
    }

    public String getPayoutAccountInn() {
        return this.payoutAccountInn;
    }

    public void setPayoutAccountInn(String payoutAccountInn) {
        this.payoutAccountInn = payoutAccountInn;
    }

    public String getPayoutAccountPurpose() {
        return this.payoutAccountPurpose;
    }

    public void setPayoutAccountPurpose(String payoutAccountPurpose) {
        this.payoutAccountPurpose = payoutAccountPurpose;
    }

    public String getPayoutAccountLegalAgreementId() {
        return this.payoutAccountLegalAgreementId;
    }

    public void setPayoutAccountLegalAgreementId(String payoutAccountLegalAgreementId) {
        this.payoutAccountLegalAgreementId = payoutAccountLegalAgreementId;
    }

    public LocalDateTime getPayoutAccountLegalAgreementSignedAt() {
        return this.payoutAccountLegalAgreementSignedAt;
    }

    public void setPayoutAccountLegalAgreementSignedAt(LocalDateTime payoutAccountLegalAgreementSignedAt) {
        this.payoutAccountLegalAgreementSignedAt = payoutAccountLegalAgreementSignedAt;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getPayoutAccountType() {
        return this.payoutAccountType;
    }

    public void setPayoutAccountType(String payoutAccountType) {
        this.payoutAccountType = payoutAccountType;
    }

    public String getPayoutAccountBankAddress() {
        return this.payoutAccountBankAddress;
    }

    public void setPayoutAccountBankAddress(String payoutAccountBankAddress) {
        this.payoutAccountBankAddress = payoutAccountBankAddress;
    }

    public String getPayoutAccountBankBic() {
        return this.payoutAccountBankBic;
    }

    public void setPayoutAccountBankBic(String payoutAccountBankBic) {
        this.payoutAccountBankBic = payoutAccountBankBic;
    }

    public String getPayoutAccountBankIban() {
        return this.payoutAccountBankIban;
    }

    public void setPayoutAccountBankIban(String payoutAccountBankIban) {
        this.payoutAccountBankIban = payoutAccountBankIban;
    }

    public String getPayoutAccountLegalName() {
        return this.payoutAccountLegalName;
    }

    public void setPayoutAccountLegalName(String payoutAccountLegalName) {
        this.payoutAccountLegalName = payoutAccountLegalName;
    }

    public String getPayoutAccountTradingName() {
        return this.payoutAccountTradingName;
    }

    public void setPayoutAccountTradingName(String payoutAccountTradingName) {
        this.payoutAccountTradingName = payoutAccountTradingName;
    }

    public String getPayoutAccountRegisteredAddress() {
        return this.payoutAccountRegisteredAddress;
    }

    public void setPayoutAccountRegisteredAddress(String payoutAccountRegisteredAddress) {
        this.payoutAccountRegisteredAddress = payoutAccountRegisteredAddress;
    }

    public String getPayoutAccountActualAddress() {
        return this.payoutAccountActualAddress;
    }

    public void setPayoutAccountActualAddress(String payoutAccountActualAddress) {
        this.payoutAccountActualAddress = payoutAccountActualAddress;
    }

    public String getPayoutAccountRegisteredNumber() {
        return this.payoutAccountRegisteredNumber;
    }

    public void setPayoutAccountRegisteredNumber(String payoutAccountRegisteredNumber) {
        this.payoutAccountRegisteredNumber = payoutAccountRegisteredNumber;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PayoutEvent other = (PayoutEvent) obj;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (eventCreatedAt == null) {
            if (other.eventCreatedAt != null)
                return false;
        }
        else if (!eventCreatedAt.equals(other.eventCreatedAt))
            return false;
        if (eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!eventType.equals(other.eventType))
            return false;
        if (payoutId == null) {
            if (other.payoutId != null)
                return false;
        }
        else if (!payoutId.equals(other.payoutId))
            return false;
        if (payoutPartyId == null) {
            if (other.payoutPartyId != null)
                return false;
        }
        else if (!payoutPartyId.equals(other.payoutPartyId))
            return false;
        if (payoutShopId == null) {
            if (other.payoutShopId != null)
                return false;
        }
        else if (!payoutShopId.equals(other.payoutShopId))
            return false;
        if (payoutCreatedAt == null) {
            if (other.payoutCreatedAt != null)
                return false;
        }
        else if (!payoutCreatedAt.equals(other.payoutCreatedAt))
            return false;
        if (payoutStatus == null) {
            if (other.payoutStatus != null)
                return false;
        }
        else if (!payoutStatus.equals(other.payoutStatus))
            return false;
        if (payoutStatusCancelDetails == null) {
            if (other.payoutStatusCancelDetails != null)
                return false;
        }
        else if (!payoutStatusCancelDetails.equals(other.payoutStatusCancelDetails))
            return false;
        if (payoutType == null) {
            if (other.payoutType != null)
                return false;
        }
        else if (!payoutType.equals(other.payoutType))
            return false;
        if (payoutCashFlow == null) {
            if (other.payoutCashFlow != null)
                return false;
        }
        else if (!payoutCashFlow.equals(other.payoutCashFlow))
            return false;
        if (payoutPaidDetailsType == null) {
            if (other.payoutPaidDetailsType != null)
                return false;
        }
        else if (!payoutPaidDetailsType.equals(other.payoutPaidDetailsType))
            return false;
        if (payoutCardToken == null) {
            if (other.payoutCardToken != null)
                return false;
        }
        else if (!payoutCardToken.equals(other.payoutCardToken))
            return false;
        if (payoutCardPaymentSystem == null) {
            if (other.payoutCardPaymentSystem != null)
                return false;
        }
        else if (!payoutCardPaymentSystem.equals(other.payoutCardPaymentSystem))
            return false;
        if (payoutCardBin == null) {
            if (other.payoutCardBin != null)
                return false;
        }
        else if (!payoutCardBin.equals(other.payoutCardBin))
            return false;
        if (payoutCardMaskedPan == null) {
            if (other.payoutCardMaskedPan != null)
                return false;
        }
        else if (!payoutCardMaskedPan.equals(other.payoutCardMaskedPan))
            return false;
        if (payoutCardProviderName == null) {
            if (other.payoutCardProviderName != null)
                return false;
        }
        else if (!payoutCardProviderName.equals(other.payoutCardProviderName))
            return false;
        if (payoutCardProviderTransactionId == null) {
            if (other.payoutCardProviderTransactionId != null)
                return false;
        }
        else if (!payoutCardProviderTransactionId.equals(other.payoutCardProviderTransactionId))
            return false;
        if (payoutAccountId == null) {
            if (other.payoutAccountId != null)
                return false;
        }
        else if (!payoutAccountId.equals(other.payoutAccountId))
            return false;
        if (payoutAccountBankName == null) {
            if (other.payoutAccountBankName != null)
                return false;
        }
        else if (!payoutAccountBankName.equals(other.payoutAccountBankName))
            return false;
        if (payoutAccountBankPostId == null) {
            if (other.payoutAccountBankPostId != null)
                return false;
        }
        else if (!payoutAccountBankPostId.equals(other.payoutAccountBankPostId))
            return false;
        if (payoutAccountBankLocalCode == null) {
            if (other.payoutAccountBankLocalCode != null)
                return false;
        }
        else if (!payoutAccountBankLocalCode.equals(other.payoutAccountBankLocalCode))
            return false;
        if (payoutAccountInn == null) {
            if (other.payoutAccountInn != null)
                return false;
        }
        else if (!payoutAccountInn.equals(other.payoutAccountInn))
            return false;
        if (payoutAccountPurpose == null) {
            if (other.payoutAccountPurpose != null)
                return false;
        }
        else if (!payoutAccountPurpose.equals(other.payoutAccountPurpose))
            return false;
        if (payoutAccountLegalAgreementId == null) {
            if (other.payoutAccountLegalAgreementId != null)
                return false;
        }
        else if (!payoutAccountLegalAgreementId.equals(other.payoutAccountLegalAgreementId))
            return false;
        if (payoutAccountLegalAgreementSignedAt == null) {
            if (other.payoutAccountLegalAgreementSignedAt != null)
                return false;
        }
        else if (!payoutAccountLegalAgreementSignedAt.equals(other.payoutAccountLegalAgreementSignedAt))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (userType == null) {
            if (other.userType != null)
                return false;
        }
        else if (!userType.equals(other.userType))
            return false;
        if (payoutAccountType == null) {
            if (other.payoutAccountType != null)
                return false;
        }
        else if (!payoutAccountType.equals(other.payoutAccountType))
            return false;
        if (payoutAccountBankAddress == null) {
            if (other.payoutAccountBankAddress != null)
                return false;
        }
        else if (!payoutAccountBankAddress.equals(other.payoutAccountBankAddress))
            return false;
        if (payoutAccountBankBic == null) {
            if (other.payoutAccountBankBic != null)
                return false;
        }
        else if (!payoutAccountBankBic.equals(other.payoutAccountBankBic))
            return false;
        if (payoutAccountBankIban == null) {
            if (other.payoutAccountBankIban != null)
                return false;
        }
        else if (!payoutAccountBankIban.equals(other.payoutAccountBankIban))
            return false;
        if (payoutAccountLegalName == null) {
            if (other.payoutAccountLegalName != null)
                return false;
        }
        else if (!payoutAccountLegalName.equals(other.payoutAccountLegalName))
            return false;
        if (payoutAccountTradingName == null) {
            if (other.payoutAccountTradingName != null)
                return false;
        }
        else if (!payoutAccountTradingName.equals(other.payoutAccountTradingName))
            return false;
        if (payoutAccountRegisteredAddress == null) {
            if (other.payoutAccountRegisteredAddress != null)
                return false;
        }
        else if (!payoutAccountRegisteredAddress.equals(other.payoutAccountRegisteredAddress))
            return false;
        if (payoutAccountActualAddress == null) {
            if (other.payoutAccountActualAddress != null)
                return false;
        }
        else if (!payoutAccountActualAddress.equals(other.payoutAccountActualAddress))
            return false;
        if (payoutAccountRegisteredNumber == null) {
            if (other.payoutAccountRegisteredNumber != null)
                return false;
        }
        else if (!payoutAccountRegisteredNumber.equals(other.payoutAccountRegisteredNumber))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.eventCreatedAt == null) ? 0 : this.eventCreatedAt.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.payoutId == null) ? 0 : this.payoutId.hashCode());
        result = prime * result + ((this.payoutPartyId == null) ? 0 : this.payoutPartyId.hashCode());
        result = prime * result + ((this.payoutShopId == null) ? 0 : this.payoutShopId.hashCode());
        result = prime * result + ((this.payoutCreatedAt == null) ? 0 : this.payoutCreatedAt.hashCode());
        result = prime * result + ((this.payoutStatus == null) ? 0 : this.payoutStatus.hashCode());
        result = prime * result + ((this.payoutStatusCancelDetails == null) ? 0 : this.payoutStatusCancelDetails.hashCode());
        result = prime * result + ((this.payoutType == null) ? 0 : this.payoutType.hashCode());
        result = prime * result + ((this.payoutCashFlow == null) ? 0 : this.payoutCashFlow.hashCode());
        result = prime * result + ((this.payoutPaidDetailsType == null) ? 0 : this.payoutPaidDetailsType.hashCode());
        result = prime * result + ((this.payoutCardToken == null) ? 0 : this.payoutCardToken.hashCode());
        result = prime * result + ((this.payoutCardPaymentSystem == null) ? 0 : this.payoutCardPaymentSystem.hashCode());
        result = prime * result + ((this.payoutCardBin == null) ? 0 : this.payoutCardBin.hashCode());
        result = prime * result + ((this.payoutCardMaskedPan == null) ? 0 : this.payoutCardMaskedPan.hashCode());
        result = prime * result + ((this.payoutCardProviderName == null) ? 0 : this.payoutCardProviderName.hashCode());
        result = prime * result + ((this.payoutCardProviderTransactionId == null) ? 0 : this.payoutCardProviderTransactionId.hashCode());
        result = prime * result + ((this.payoutAccountId == null) ? 0 : this.payoutAccountId.hashCode());
        result = prime * result + ((this.payoutAccountBankName == null) ? 0 : this.payoutAccountBankName.hashCode());
        result = prime * result + ((this.payoutAccountBankPostId == null) ? 0 : this.payoutAccountBankPostId.hashCode());
        result = prime * result + ((this.payoutAccountBankLocalCode == null) ? 0 : this.payoutAccountBankLocalCode.hashCode());
        result = prime * result + ((this.payoutAccountInn == null) ? 0 : this.payoutAccountInn.hashCode());
        result = prime * result + ((this.payoutAccountPurpose == null) ? 0 : this.payoutAccountPurpose.hashCode());
        result = prime * result + ((this.payoutAccountLegalAgreementId == null) ? 0 : this.payoutAccountLegalAgreementId.hashCode());
        result = prime * result + ((this.payoutAccountLegalAgreementSignedAt == null) ? 0 : this.payoutAccountLegalAgreementSignedAt.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.userType == null) ? 0 : this.userType.hashCode());
        result = prime * result + ((this.payoutAccountType == null) ? 0 : this.payoutAccountType.hashCode());
        result = prime * result + ((this.payoutAccountBankAddress == null) ? 0 : this.payoutAccountBankAddress.hashCode());
        result = prime * result + ((this.payoutAccountBankBic == null) ? 0 : this.payoutAccountBankBic.hashCode());
        result = prime * result + ((this.payoutAccountBankIban == null) ? 0 : this.payoutAccountBankIban.hashCode());
        result = prime * result + ((this.payoutAccountLegalName == null) ? 0 : this.payoutAccountLegalName.hashCode());
        result = prime * result + ((this.payoutAccountTradingName == null) ? 0 : this.payoutAccountTradingName.hashCode());
        result = prime * result + ((this.payoutAccountRegisteredAddress == null) ? 0 : this.payoutAccountRegisteredAddress.hashCode());
        result = prime * result + ((this.payoutAccountActualAddress == null) ? 0 : this.payoutAccountActualAddress.hashCode());
        result = prime * result + ((this.payoutAccountRegisteredNumber == null) ? 0 : this.payoutAccountRegisteredNumber.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PayoutEvent (");

        sb.append(eventId);
        sb.append(", ").append(eventCreatedAt);
        sb.append(", ").append(eventType);
        sb.append(", ").append(payoutId);
        sb.append(", ").append(payoutPartyId);
        sb.append(", ").append(payoutShopId);
        sb.append(", ").append(payoutCreatedAt);
        sb.append(", ").append(payoutStatus);
        sb.append(", ").append(payoutStatusCancelDetails);
        sb.append(", ").append(payoutType);
        sb.append(", ").append(payoutCashFlow);
        sb.append(", ").append(payoutPaidDetailsType);
        sb.append(", ").append(payoutCardToken);
        sb.append(", ").append(payoutCardPaymentSystem);
        sb.append(", ").append(payoutCardBin);
        sb.append(", ").append(payoutCardMaskedPan);
        sb.append(", ").append(payoutCardProviderName);
        sb.append(", ").append(payoutCardProviderTransactionId);
        sb.append(", ").append(payoutAccountId);
        sb.append(", ").append(payoutAccountBankName);
        sb.append(", ").append(payoutAccountBankPostId);
        sb.append(", ").append(payoutAccountBankLocalCode);
        sb.append(", ").append(payoutAccountInn);
        sb.append(", ").append(payoutAccountPurpose);
        sb.append(", ").append(payoutAccountLegalAgreementId);
        sb.append(", ").append(payoutAccountLegalAgreementSignedAt);
        sb.append(", ").append(userId);
        sb.append(", ").append(userType);
        sb.append(", ").append(payoutAccountType);
        sb.append(", ").append(payoutAccountBankAddress);
        sb.append(", ").append(payoutAccountBankBic);
        sb.append(", ").append(payoutAccountBankIban);
        sb.append(", ").append(payoutAccountLegalName);
        sb.append(", ").append(payoutAccountTradingName);
        sb.append(", ").append(payoutAccountRegisteredAddress);
        sb.append(", ").append(payoutAccountActualAddress);
        sb.append(", ").append(payoutAccountRegisteredNumber);

        sb.append(")");
        return sb.toString();
    }
}
