/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import com.rbkmoney.payouter.domain.enums.RefundStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Refund implements Serializable {

    private static final long serialVersionUID = 1534528379;

    private Long          id;
    private Long          eventId;
    private String        shopId;
    private String        partyId;
    private String        invoiceId;
    private String        paymentId;
    private String        refundId;
    private RefundStatus  status;
    private LocalDateTime createdAt;
    private String        reason;
    private Long          amount;
    private Long          fee;
    private Long          payoutId;
    private LocalDateTime succeededAt;
    private Long          domainRevision;
    private String        currencyCode;

    public Refund() {}

    public Refund(Refund value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.shopId = value.shopId;
        this.partyId = value.partyId;
        this.invoiceId = value.invoiceId;
        this.paymentId = value.paymentId;
        this.refundId = value.refundId;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.reason = value.reason;
        this.amount = value.amount;
        this.fee = value.fee;
        this.payoutId = value.payoutId;
        this.succeededAt = value.succeededAt;
        this.domainRevision = value.domainRevision;
        this.currencyCode = value.currencyCode;
    }

    public Refund(
        Long          id,
        Long          eventId,
        String        shopId,
        String        partyId,
        String        invoiceId,
        String        paymentId,
        String        refundId,
        RefundStatus  status,
        LocalDateTime createdAt,
        String        reason,
        Long          amount,
        Long          fee,
        Long          payoutId,
        LocalDateTime succeededAt,
        Long          domainRevision,
        String        currencyCode
    ) {
        this.id = id;
        this.eventId = eventId;
        this.shopId = shopId;
        this.partyId = partyId;
        this.invoiceId = invoiceId;
        this.paymentId = paymentId;
        this.refundId = refundId;
        this.status = status;
        this.createdAt = createdAt;
        this.reason = reason;
        this.amount = amount;
        this.fee = fee;
        this.payoutId = payoutId;
        this.succeededAt = succeededAt;
        this.domainRevision = domainRevision;
        this.currencyCode = currencyCode;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return this.eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getInvoiceId() {
        return this.invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getPaymentId() {
        return this.paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public String getRefundId() {
        return this.refundId;
    }

    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    public RefundStatus getStatus() {
        return this.status;
    }

    public void setStatus(RefundStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Long getAmount() {
        return this.amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getFee() {
        return this.fee;
    }

    public void setFee(Long fee) {
        this.fee = fee;
    }

    public Long getPayoutId() {
        return this.payoutId;
    }

    public void setPayoutId(Long payoutId) {
        this.payoutId = payoutId;
    }

    public LocalDateTime getSucceededAt() {
        return this.succeededAt;
    }

    public void setSucceededAt(LocalDateTime succeededAt) {
        this.succeededAt = succeededAt;
    }

    public Long getDomainRevision() {
        return this.domainRevision;
    }

    public void setDomainRevision(Long domainRevision) {
        this.domainRevision = domainRevision;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Refund other = (Refund) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!eventId.equals(other.eventId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (invoiceId == null) {
            if (other.invoiceId != null)
                return false;
        }
        else if (!invoiceId.equals(other.invoiceId))
            return false;
        if (paymentId == null) {
            if (other.paymentId != null)
                return false;
        }
        else if (!paymentId.equals(other.paymentId))
            return false;
        if (refundId == null) {
            if (other.refundId != null)
                return false;
        }
        else if (!refundId.equals(other.refundId))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (reason == null) {
            if (other.reason != null)
                return false;
        }
        else if (!reason.equals(other.reason))
            return false;
        if (amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!amount.equals(other.amount))
            return false;
        if (fee == null) {
            if (other.fee != null)
                return false;
        }
        else if (!fee.equals(other.fee))
            return false;
        if (payoutId == null) {
            if (other.payoutId != null)
                return false;
        }
        else if (!payoutId.equals(other.payoutId))
            return false;
        if (succeededAt == null) {
            if (other.succeededAt != null)
                return false;
        }
        else if (!succeededAt.equals(other.succeededAt))
            return false;
        if (domainRevision == null) {
            if (other.domainRevision != null)
                return false;
        }
        else if (!domainRevision.equals(other.domainRevision))
            return false;
        if (currencyCode == null) {
            if (other.currencyCode != null)
                return false;
        }
        else if (!currencyCode.equals(other.currencyCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.invoiceId == null) ? 0 : this.invoiceId.hashCode());
        result = prime * result + ((this.paymentId == null) ? 0 : this.paymentId.hashCode());
        result = prime * result + ((this.refundId == null) ? 0 : this.refundId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.reason == null) ? 0 : this.reason.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        result = prime * result + ((this.fee == null) ? 0 : this.fee.hashCode());
        result = prime * result + ((this.payoutId == null) ? 0 : this.payoutId.hashCode());
        result = prime * result + ((this.succeededAt == null) ? 0 : this.succeededAt.hashCode());
        result = prime * result + ((this.domainRevision == null) ? 0 : this.domainRevision.hashCode());
        result = prime * result + ((this.currencyCode == null) ? 0 : this.currencyCode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Refund (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(partyId);
        sb.append(", ").append(invoiceId);
        sb.append(", ").append(paymentId);
        sb.append(", ").append(refundId);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(reason);
        sb.append(", ").append(amount);
        sb.append(", ").append(fee);
        sb.append(", ").append(payoutId);
        sb.append(", ").append(succeededAt);
        sb.append(", ").append(domainRevision);
        sb.append(", ").append(currencyCode);

        sb.append(")");
        return sb.toString();
    }
}
