/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Report implements Serializable {

    private static final long serialVersionUID = -87595167;

    private Long          id;
    private LocalDateTime createdAt;
    private String        payoutids;
    private String        name;
    private String        content;
    private String        description;

    public Report() {}

    public Report(Report value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.payoutids = value.payoutids;
        this.name = value.name;
        this.content = value.content;
        this.description = value.description;
    }

    public Report(
        Long          id,
        LocalDateTime createdAt,
        String        payoutids,
        String        name,
        String        content,
        String        description
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.payoutids = payoutids;
        this.name = name;
        this.content = content;
        this.description = description;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getPayoutids() {
        return this.payoutids;
    }

    public void setPayoutids(String payoutids) {
        this.payoutids = payoutids;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Report other = (Report) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (payoutids == null) {
            if (other.payoutids != null)
                return false;
        }
        else if (!payoutids.equals(other.payoutids))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (content == null) {
            if (other.content != null)
                return false;
        }
        else if (!content.equals(other.content))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.payoutids == null) ? 0 : this.payoutids.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(payoutids);
        sb.append(", ").append(name);
        sb.append(", ").append(content);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
