/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import com.rbkmoney.payouter.domain.enums.ReportStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Report implements Serializable {

    private static final long serialVersionUID = 531648696;

    private Long          id;
    private LocalDateTime createdAt;
    private String        payoutIds;
    private String        name;
    private String        content;
    private String        description;
    private ReportStatus  status;
    private LocalDateTime lastSendAt;
    private String        subject;
    private String        encoding;

    public Report() {}

    public Report(Report value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.payoutIds = value.payoutIds;
        this.name = value.name;
        this.content = value.content;
        this.description = value.description;
        this.status = value.status;
        this.lastSendAt = value.lastSendAt;
        this.subject = value.subject;
        this.encoding = value.encoding;
    }

    public Report(
        Long          id,
        LocalDateTime createdAt,
        String        payoutIds,
        String        name,
        String        content,
        String        description,
        ReportStatus  status,
        LocalDateTime lastSendAt,
        String        subject,
        String        encoding
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.payoutIds = payoutIds;
        this.name = name;
        this.content = content;
        this.description = description;
        this.status = status;
        this.lastSendAt = lastSendAt;
        this.subject = subject;
        this.encoding = encoding;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getPayoutIds() {
        return this.payoutIds;
    }

    public void setPayoutIds(String payoutIds) {
        this.payoutIds = payoutIds;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ReportStatus getStatus() {
        return this.status;
    }

    public void setStatus(ReportStatus status) {
        this.status = status;
    }

    public LocalDateTime getLastSendAt() {
        return this.lastSendAt;
    }

    public void setLastSendAt(LocalDateTime lastSendAt) {
        this.lastSendAt = lastSendAt;
    }

    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getEncoding() {
        return this.encoding;
    }

    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Report other = (Report) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (payoutIds == null) {
            if (other.payoutIds != null)
                return false;
        }
        else if (!payoutIds.equals(other.payoutIds))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (content == null) {
            if (other.content != null)
                return false;
        }
        else if (!content.equals(other.content))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (lastSendAt == null) {
            if (other.lastSendAt != null)
                return false;
        }
        else if (!lastSendAt.equals(other.lastSendAt))
            return false;
        if (subject == null) {
            if (other.subject != null)
                return false;
        }
        else if (!subject.equals(other.subject))
            return false;
        if (encoding == null) {
            if (other.encoding != null)
                return false;
        }
        else if (!encoding.equals(other.encoding))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.payoutIds == null) ? 0 : this.payoutIds.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.lastSendAt == null) ? 0 : this.lastSendAt.hashCode());
        result = prime * result + ((this.subject == null) ? 0 : this.subject.hashCode());
        result = prime * result + ((this.encoding == null) ? 0 : this.encoding.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(payoutIds);
        sb.append(", ").append(name);
        sb.append(", ").append(content);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(lastSendAt);
        sb.append(", ").append(subject);
        sb.append(", ").append(encoding);

        sb.append(")");
        return sb.toString();
    }
}
