/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopMeta implements Serializable {

    private static final long serialVersionUID = -298910419;

    private String        partyId;
    private String        shopId;
    private LocalDateTime wtime;

    public ShopMeta() {}

    public ShopMeta(ShopMeta value) {
        this.partyId = value.partyId;
        this.shopId = value.shopId;
        this.wtime = value.wtime;
    }

    public ShopMeta(
        String        partyId,
        String        shopId,
        LocalDateTime wtime
    ) {
        this.partyId = partyId;
        this.shopId = shopId;
        this.wtime = wtime;
    }

    public String getPartyId() {
        return this.partyId;
    }

    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }

    public String getShopId() {
        return this.shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    public LocalDateTime getWtime() {
        return this.wtime;
    }

    public void setWtime(LocalDateTime wtime) {
        this.wtime = wtime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ShopMeta other = (ShopMeta) obj;
        if (partyId == null) {
            if (other.partyId != null)
                return false;
        }
        else if (!partyId.equals(other.partyId))
            return false;
        if (shopId == null) {
            if (other.shopId != null)
                return false;
        }
        else if (!shopId.equals(other.shopId))
            return false;
        if (wtime == null) {
            if (other.wtime != null)
                return false;
        }
        else if (!wtime.equals(other.wtime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.partyId == null) ? 0 : this.partyId.hashCode());
        result = prime * result + ((this.shopId == null) ? 0 : this.shopId.hashCode());
        result = prime * result + ((this.wtime == null) ? 0 : this.wtime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopMeta (");

        sb.append(partyId);
        sb.append(", ").append(shopId);
        sb.append(", ").append(wtime);

        sb.append(")");
        return sb.toString();
    }
}
