/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.enums;


import com.rbkmoney.payouter.domain.Sht;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AccountType implements EnumType {

    MERCHANT_SETTLEMENT("MERCHANT_SETTLEMENT"),

    MERCHANT_GUARANTEE("MERCHANT_GUARANTEE"),

    MERCHANT_PAYOUT("MERCHANT_PAYOUT"),

    PROVIDER_SETTLEMENT("PROVIDER_SETTLEMENT"),

    SYSTEM_SETTLEMENT("SYSTEM_SETTLEMENT"),

    EXTERNAL_INCOME("EXTERNAL_INCOME"),

    EXTERNAL_OUTCOME("EXTERNAL_OUTCOME");

    private final String literal;

    private AccountType(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sht.SHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "account_type";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
