/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in sht
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>sht.adjustment_id_seq</code>
     */
    public static final Sequence<Long> ADJUSTMENT_ID_SEQ = new SequenceImpl<Long>("adjustment_id_seq", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>sht.payment_id_seq</code>
     */
    public static final Sequence<Long> PAYMENT_ID_SEQ = new SequenceImpl<Long>("payment_id_seq", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>sht.payout_event_id_sequence</code>
     */
    public static final Sequence<Long> PAYOUT_EVENT_ID_SEQUENCE = new SequenceImpl<Long>("payout_event_id_sequence", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>sht.payout_id_sequence</code>
     */
    public static final Sequence<Long> PAYOUT_ID_SEQUENCE = new SequenceImpl<Long>("payout_id_sequence", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>sht.refund_id_seq</code>
     */
    public static final Sequence<Long> REFUND_ID_SEQ = new SequenceImpl<Long>("refund_id_seq", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>sht.report_id_seq</code>
     */
    public static final Sequence<Long> REPORT_ID_SEQ = new SequenceImpl<Long>("report_id_seq", Sht.SHT, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
