/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables;


import com.rbkmoney.payouter.domain.Sht;
import com.rbkmoney.payouter.domain.tables.records.EventStockMetaRecord;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventStockMeta extends TableImpl<EventStockMetaRecord> {

    private static final long serialVersionUID = -1049724880;

    /**
     * The reference instance of <code>sht.event_stock_meta</code>
     */
    public static final EventStockMeta EVENT_STOCK_META = new EventStockMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventStockMetaRecord> getRecordType() {
        return EventStockMetaRecord.class;
    }

    /**
     * The column <code>sht.event_stock_meta.last_event_id</code>.
     */
    public final TableField<EventStockMetaRecord, Long> LAST_EVENT_ID = createField("last_event_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>sht.event_stock_meta.last_event_created_at</code>.
     */
    public final TableField<EventStockMetaRecord, LocalDateTime> LAST_EVENT_CREATED_AT = createField("last_event_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>sht.event_stock_meta</code> table reference
     */
    public EventStockMeta() {
        this("event_stock_meta", null);
    }

    /**
     * Create an aliased <code>sht.event_stock_meta</code> table reference
     */
    public EventStockMeta(String alias) {
        this(alias, EVENT_STOCK_META);
    }

    private EventStockMeta(String alias, Table<EventStockMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventStockMeta(String alias, Table<EventStockMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sht.SHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventStockMeta as(String alias) {
        return new EventStockMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventStockMeta rename(String name) {
        return new EventStockMeta(name, null);
    }
}
