/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables;


import com.rbkmoney.payouter.domain.Keys;
import com.rbkmoney.payouter.domain.Sht;
import com.rbkmoney.payouter.domain.tables.records.ShopMetaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopMeta extends TableImpl<ShopMetaRecord> {

    private static final long serialVersionUID = -2071095373;

    /**
     * The reference instance of <code>sht.shop_meta</code>
     */
    public static final ShopMeta SHOP_META = new ShopMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShopMetaRecord> getRecordType() {
        return ShopMetaRecord.class;
    }

    /**
     * The column <code>sht.shop_meta.party_id</code>.
     */
    public final TableField<ShopMetaRecord, String> PARTY_ID = createField("party_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sht.shop_meta.shop_id</code>.
     */
    public final TableField<ShopMetaRecord, String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sht.shop_meta.wtime</code>.
     */
    public final TableField<ShopMetaRecord, LocalDateTime> WTIME = createField("wtime", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sht.shop_meta.last_payout_created_at</code>.
     */
    public final TableField<ShopMetaRecord, LocalDateTime> LAST_PAYOUT_CREATED_AT = createField("last_payout_created_at", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>sht.shop_meta</code> table reference
     */
    public ShopMeta() {
        this("shop_meta", null);
    }

    /**
     * Create an aliased <code>sht.shop_meta</code> table reference
     */
    public ShopMeta(String alias) {
        this(alias, SHOP_META);
    }

    private ShopMeta(String alias, Table<ShopMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ShopMeta(String alias, Table<ShopMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sht.SHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ShopMetaRecord> getPrimaryKey() {
        return Keys.SHOP_META_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ShopMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<ShopMetaRecord>>asList(Keys.SHOP_META_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopMeta as(String alias) {
        return new ShopMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShopMeta rename(String name) {
        return new ShopMeta(name, null);
    }
}
