/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.AdjustmentStatus;
import com.rbkmoney.payouter.domain.tables.Adjustment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdjustmentRecord extends UpdatableRecordImpl<AdjustmentRecord> implements Record17<Long, Long, String, String, String, String, String, AdjustmentStatus, LocalDateTime, Long, String, Long, Long, Long, Long, LocalDateTime, Long> {

    private static final long serialVersionUID = 1906140220;

    /**
     * Setter for <code>sht.adjustment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.adjustment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.adjustment.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.adjustment.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sht.adjustment.shop_id</code>.
     */
    public void setShopId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.adjustment.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.adjustment.party_id</code>.
     */
    public void setPartyId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.adjustment.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sht.adjustment.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.adjustment.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sht.adjustment.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.adjustment.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sht.adjustment.adjustment_id</code>.
     */
    public void setAdjustmentId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.adjustment.adjustment_id</code>.
     */
    public String getAdjustmentId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sht.adjustment.status</code>.
     */
    public void setStatus(AdjustmentStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>sht.adjustment.status</code>.
     */
    public AdjustmentStatus getStatus() {
        return (AdjustmentStatus) get(7);
    }

    /**
     * Setter for <code>sht.adjustment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sht.adjustment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>sht.adjustment.domain_revision</code>.
     */
    public void setDomainRevision(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>sht.adjustment.domain_revision</code>.
     */
    public Long getDomainRevision() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>sht.adjustment.reason</code>.
     */
    public void setReason(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>sht.adjustment.reason</code>.
     */
    public String getReason() {
        return (String) get(10);
    }

    /**
     * Setter for <code>sht.adjustment.new_amount</code>.
     */
    public void setNewAmount(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>sht.adjustment.new_amount</code>.
     */
    public Long getNewAmount() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>sht.adjustment.new_provider_fee</code>.
     */
    public void setNewProviderFee(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>sht.adjustment.new_provider_fee</code>.
     */
    public Long getNewProviderFee() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>sht.adjustment.new_fee</code>.
     */
    public void setNewFee(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>sht.adjustment.new_fee</code>.
     */
    public Long getNewFee() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>sht.adjustment.new_external_fee</code>.
     */
    public void setNewExternalFee(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>sht.adjustment.new_external_fee</code>.
     */
    public Long getNewExternalFee() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>sht.adjustment.captured_at</code>.
     */
    public void setCapturedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>sht.adjustment.captured_at</code>.
     */
    public LocalDateTime getCapturedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>sht.adjustment.payout_id</code>.
     */
    public void setPayoutId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>sht.adjustment.payout_id</code>.
     */
    public Long getPayoutId() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, String, String, String, AdjustmentStatus, LocalDateTime, Long, String, Long, Long, Long, Long, LocalDateTime, Long> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, Long, String, String, String, String, String, AdjustmentStatus, LocalDateTime, Long, String, Long, Long, Long, Long, LocalDateTime, Long> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Adjustment.ADJUSTMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Adjustment.ADJUSTMENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Adjustment.ADJUSTMENT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Adjustment.ADJUSTMENT.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Adjustment.ADJUSTMENT.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Adjustment.ADJUSTMENT.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Adjustment.ADJUSTMENT.ADJUSTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AdjustmentStatus> field8() {
        return Adjustment.ADJUSTMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Adjustment.ADJUSTMENT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Adjustment.ADJUSTMENT.DOMAIN_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Adjustment.ADJUSTMENT.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Adjustment.ADJUSTMENT.NEW_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Adjustment.ADJUSTMENT.NEW_PROVIDER_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return Adjustment.ADJUSTMENT.NEW_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Adjustment.ADJUSTMENT.NEW_EXTERNAL_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return Adjustment.ADJUSTMENT.CAPTURED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Adjustment.ADJUSTMENT.PAYOUT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAdjustmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentStatus value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getDomainRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getNewAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getNewProviderFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getNewFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getNewExternalFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getCapturedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value3(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value4(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value5(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value6(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value7(String value) {
        setAdjustmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value8(AdjustmentStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value10(Long value) {
        setDomainRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value11(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value12(Long value) {
        setNewAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value13(Long value) {
        setNewProviderFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value14(Long value) {
        setNewFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value15(Long value) {
        setNewExternalFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value16(LocalDateTime value) {
        setCapturedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord value17(Long value) {
        setPayoutId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AdjustmentRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, AdjustmentStatus value8, LocalDateTime value9, Long value10, String value11, Long value12, Long value13, Long value14, Long value15, LocalDateTime value16, Long value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdjustmentRecord
     */
    public AdjustmentRecord() {
        super(Adjustment.ADJUSTMENT);
    }

    /**
     * Create a detached, initialised AdjustmentRecord
     */
    public AdjustmentRecord(Long id, Long eventId, String shopId, String partyId, String invoiceId, String paymentId, String adjustmentId, AdjustmentStatus status, LocalDateTime createdAt, Long domainRevision, String reason, Long newAmount, Long newProviderFee, Long newFee, Long newExternalFee, LocalDateTime capturedAt, Long payoutId) {
        super(Adjustment.ADJUSTMENT);

        set(0, id);
        set(1, eventId);
        set(2, shopId);
        set(3, partyId);
        set(4, invoiceId);
        set(5, paymentId);
        set(6, adjustmentId);
        set(7, status);
        set(8, createdAt);
        set(9, domainRevision);
        set(10, reason);
        set(11, newAmount);
        set(12, newProviderFee);
        set(13, newFee);
        set(14, newExternalFee);
        set(15, capturedAt);
        set(16, payoutId);
    }
}
