/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.CashFlowType;
import com.rbkmoney.payouter.domain.tables.CashFlowDescription;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CashFlowDescriptionRecord extends UpdatableRecordImpl<CashFlowDescriptionRecord> implements Record7<Long, Long, CashFlowType, Long, Long, String, String> {

    private static final long serialVersionUID = 1156189106;

    /**
     * Setter for <code>sht.cash_flow_description.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.cash_flow_description.payout_id</code>.
     */
    public void setPayoutId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.payout_id</code>.
     */
    public Long getPayoutId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sht.cash_flow_description.cash_flow_type</code>.
     */
    public void setCashFlowType(CashFlowType value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.cash_flow_type</code>.
     */
    public CashFlowType getCashFlowType() {
        return (CashFlowType) get(2);
    }

    /**
     * Setter for <code>sht.cash_flow_description.count</code>.
     */
    public void setCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.count</code>.
     */
    public Long getCount() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>sht.cash_flow_description.amount</code>.
     */
    public void setAmount(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>sht.cash_flow_description.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sht.cash_flow_description.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.cash_flow_description.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, CashFlowType, Long, Long, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, CashFlowType, Long, Long, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.PAYOUT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<CashFlowType> field3() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.CASH_FLOW_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CashFlowDescription.CASH_FLOW_DESCRIPTION.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowType value3() {
        return getCashFlowType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value2(Long value) {
        setPayoutId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value3(CashFlowType value) {
        setCashFlowType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value4(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value5(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value6(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CashFlowDescriptionRecord values(Long value1, Long value2, CashFlowType value3, Long value4, Long value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CashFlowDescriptionRecord
     */
    public CashFlowDescriptionRecord() {
        super(CashFlowDescription.CASH_FLOW_DESCRIPTION);
    }

    /**
     * Create a detached, initialised CashFlowDescriptionRecord
     */
    public CashFlowDescriptionRecord(Long id, Long payoutId, CashFlowType cashFlowType, Long count, Long amount, String currencyCode, String description) {
        super(CashFlowDescription.CASH_FLOW_DESCRIPTION);

        set(0, id);
        set(1, payoutId);
        set(2, cashFlowType);
        set(3, count);
        set(4, amount);
        set(5, currencyCode);
        set(6, description);
    }
}
