/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.tables.EventStockMeta;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventStockMetaRecord extends TableRecordImpl<EventStockMetaRecord> implements Record2<Long, LocalDateTime> {

    private static final long serialVersionUID = -249120391;

    /**
     * Setter for <code>sht.event_stock_meta.last_event_id</code>.
     */
    public void setLastEventId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.event_stock_meta.last_event_id</code>.
     */
    public Long getLastEventId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.event_stock_meta.last_event_created_at</code>.
     */
    public void setLastEventCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.event_stock_meta.last_event_created_at</code>.
     */
    public LocalDateTime getLastEventCreatedAt() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, LocalDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return EventStockMeta.EVENT_STOCK_META.LAST_EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return EventStockMeta.EVENT_STOCK_META.LAST_EVENT_CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getLastEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getLastEventCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventStockMetaRecord value1(Long value) {
        setLastEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventStockMetaRecord value2(LocalDateTime value) {
        setLastEventCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventStockMetaRecord values(Long value1, LocalDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventStockMetaRecord
     */
    public EventStockMetaRecord() {
        super(EventStockMeta.EVENT_STOCK_META);
    }

    /**
     * Create a detached, initialised EventStockMetaRecord
     */
    public EventStockMetaRecord(Long lastEventId, LocalDateTime lastEventCreatedAt) {
        super(EventStockMeta.EVENT_STOCK_META);

        set(0, lastEventId);
        set(1, lastEventCreatedAt);
    }
}
