/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.tables.JobMeta;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobMetaRecord extends UpdatableRecordImpl<JobMetaRecord> implements Record6<String, String, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 148125361;

    /**
     * Setter for <code>sht.job_meta.party_id</code>.
     */
    public void setPartyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.job_meta.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sht.job_meta.contract_id</code>.
     */
    public void setContractId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.job_meta.contract_id</code>.
     */
    public String getContractId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sht.job_meta.payout_tool_id</code>.
     */
    public void setPayoutToolId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.job_meta.payout_tool_id</code>.
     */
    public String getPayoutToolId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.job_meta.calendar_id</code>.
     */
    public void setCalendarId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.job_meta.calendar_id</code>.
     */
    public Integer getCalendarId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sht.job_meta.scheduler_id</code>.
     */
    public void setSchedulerId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.job_meta.scheduler_id</code>.
     */
    public Integer getSchedulerId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sht.job_meta.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.job_meta.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return JobMeta.JOB_META.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobMeta.JOB_META.CONTRACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobMeta.JOB_META.PAYOUT_TOOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return JobMeta.JOB_META.CALENDAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return JobMeta.JOB_META.SCHEDULER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return JobMeta.JOB_META.WTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContractId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPayoutToolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCalendarId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSchedulerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getWtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value1(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value2(String value) {
        setContractId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value3(String value) {
        setPayoutToolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value4(Integer value) {
        setCalendarId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value5(Integer value) {
        setSchedulerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord value6(LocalDateTime value) {
        setWtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobMetaRecord values(String value1, String value2, String value3, Integer value4, Integer value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobMetaRecord
     */
    public JobMetaRecord() {
        super(JobMeta.JOB_META);
    }

    /**
     * Create a detached, initialised JobMetaRecord
     */
    public JobMetaRecord(String partyId, String contractId, String payoutToolId, Integer calendarId, Integer schedulerId, LocalDateTime wtime) {
        super(JobMeta.JOB_META);

        set(0, partyId);
        set(1, contractId);
        set(2, payoutToolId);
        set(3, calendarId);
        set(4, schedulerId);
        set(5, wtime);
    }
}
