/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.PaymentStatus;
import com.rbkmoney.payouter.domain.tables.Payment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record18<Long, Long, String, String, String, String, Integer, PaymentStatus, Long, Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> {

    private static final long serialVersionUID = -2625503;

    /**
     * Setter for <code>sht.payment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.payment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.payment.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.payment.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sht.payment.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.payment.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.payment.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.payment.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sht.payment.party_id</code>.
     */
    public void setPartyId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.payment.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sht.payment.shop_id</code>.
     */
    public void setShopId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.payment.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sht.payment.provider_id</code>.
     */
    public void setProviderId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.payment.provider_id</code>.
     */
    public Integer getProviderId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>sht.payment.status</code>.
     */
    public void setStatus(PaymentStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>sht.payment.status</code>.
     */
    public PaymentStatus getStatus() {
        return (PaymentStatus) get(7);
    }

    /**
     * Setter for <code>sht.payment.payout_id</code>.
     */
    public void setPayoutId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>sht.payment.payout_id</code>.
     */
    public Long getPayoutId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>sht.payment.amount</code>.
     */
    public void setAmount(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>sht.payment.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>sht.payment.provider_fee</code>.
     */
    public void setProviderFee(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>sht.payment.provider_fee</code>.
     */
    public Long getProviderFee() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>sht.payment.fee</code>.
     */
    public void setFee(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>sht.payment.fee</code>.
     */
    public Long getFee() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>sht.payment.external_fee</code>.
     */
    public void setExternalFee(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>sht.payment.external_fee</code>.
     */
    public Long getExternalFee() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>sht.payment.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sht.payment.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sht.payment.captured_at</code>.
     */
    public void setCapturedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>sht.payment.captured_at</code>.
     */
    public LocalDateTime getCapturedAt() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>sht.payment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>sht.payment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>sht.payment.terminal_id</code>.
     */
    public void setTerminalId(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>sht.payment.terminal_id</code>.
     */
    public Integer getTerminalId() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>sht.payment.domain_revision</code>.
     */
    public void setDomainRevision(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>sht.payment.domain_revision</code>.
     */
    public Integer getDomainRevision() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, String, String, String, Integer, PaymentStatus, Long, Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Long, Long, String, String, String, String, Integer, PaymentStatus, Long, Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Payment.PAYMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Payment.PAYMENT.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payment.PAYMENT.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payment.PAYMENT.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Payment.PAYMENT.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Payment.PAYMENT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Payment.PAYMENT.PROVIDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<PaymentStatus> field8() {
        return Payment.PAYMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Payment.PAYMENT.PAYOUT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Payment.PAYMENT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Payment.PAYMENT.PROVIDER_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Payment.PAYMENT.FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Payment.PAYMENT.EXTERNAL_FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Payment.PAYMENT.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return Payment.PAYMENT.CAPTURED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return Payment.PAYMENT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Payment.PAYMENT.TERMINAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Payment.PAYMENT.DOMAIN_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getProviderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentStatus value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getProviderFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getExternalFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getCapturedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getDomainRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value3(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value4(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value5(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value6(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value7(Integer value) {
        setProviderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value8(PaymentStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value9(Long value) {
        setPayoutId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value10(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value11(Long value) {
        setProviderFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value12(Long value) {
        setFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value13(Long value) {
        setExternalFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value14(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value15(LocalDateTime value) {
        setCapturedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value16(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value17(Integer value) {
        setTerminalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value18(Integer value) {
        setDomainRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Integer value7, PaymentStatus value8, Long value9, Long value10, Long value11, Long value12, Long value13, String value14, LocalDateTime value15, LocalDateTime value16, Integer value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(Long id, Long eventId, String invoiceId, String paymentId, String partyId, String shopId, Integer providerId, PaymentStatus status, Long payoutId, Long amount, Long providerFee, Long fee, Long externalFee, String currencyCode, LocalDateTime capturedAt, LocalDateTime createdAt, Integer terminalId, Integer domainRevision) {
        super(Payment.PAYMENT);

        set(0, id);
        set(1, eventId);
        set(2, invoiceId);
        set(3, paymentId);
        set(4, partyId);
        set(5, shopId);
        set(6, providerId);
        set(7, status);
        set(8, payoutId);
        set(9, amount);
        set(10, providerFee);
        set(11, fee);
        set(12, externalFee);
        set(13, currencyCode);
        set(14, capturedAt);
        set(15, createdAt);
        set(16, terminalId);
        set(17, domainRevision);
    }
}
