/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.PayoutAccountType;
import com.rbkmoney.payouter.domain.enums.PayoutStatus;
import com.rbkmoney.payouter.domain.enums.PayoutType;
import com.rbkmoney.payouter.domain.tables.Payout;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayoutRecord extends UpdatableRecordImpl<PayoutRecord> {

    private static final long serialVersionUID = -1349088656;

    /**
     * Setter for <code>sht.payout.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.payout.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.payout.party_id</code>.
     */
    public void setPartyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.payout.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sht.payout.shop_id</code>.
     */
    public void setShopId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.payout.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.payout.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.payout.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sht.payout.from_time</code>.
     */
    public void setFromTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.payout.from_time</code>.
     */
    public LocalDateTime getFromTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sht.payout.to_time</code>.
     */
    public void setToTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.payout.to_time</code>.
     */
    public LocalDateTime getToTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sht.payout.status</code>.
     */
    public void setStatus(PayoutStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.payout.status</code>.
     */
    public PayoutStatus getStatus() {
        return (PayoutStatus) get(6);
    }

    /**
     * Setter for <code>sht.payout.type</code>.
     */
    public void setType(PayoutType value) {
        set(7, value);
    }

    /**
     * Getter for <code>sht.payout.type</code>.
     */
    public PayoutType getType() {
        return (PayoutType) get(7);
    }

    /**
     * Setter for <code>sht.payout.amount</code>.
     */
    public void setAmount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>sht.payout.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>sht.payout.shop_acc</code>.
     */
    public void setShopAcc(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>sht.payout.shop_acc</code>.
     */
    public Long getShopAcc() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>sht.payout.shop_payout_acc</code>.
     */
    public void setShopPayoutAcc(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>sht.payout.shop_payout_acc</code>.
     */
    public Long getShopPayoutAcc() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>sht.payout.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sht.payout.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sht.payout.bank_account</code>.
     */
    public void setBankAccount(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sht.payout.bank_account</code>.
     */
    public String getBankAccount() {
        return (String) get(12);
    }

    /**
     * Setter for <code>sht.payout.bank_local_code</code>.
     */
    public void setBankLocalCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sht.payout.bank_local_code</code>.
     */
    public String getBankLocalCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sht.payout.bank_name</code>.
     */
    public void setBankName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>sht.payout.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>sht.payout.bank_post_account</code>.
     */
    public void setBankPostAccount(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sht.payout.bank_post_account</code>.
     */
    public String getBankPostAccount() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sht.payout.inn</code>.
     */
    public void setInn(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>sht.payout.inn</code>.
     */
    public String getInn() {
        return (String) get(16);
    }

    /**
     * Setter for <code>sht.payout.purpose</code>.
     */
    public void setPurpose(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>sht.payout.purpose</code>.
     */
    public String getPurpose() {
        return (String) get(17);
    }

    /**
     * Setter for <code>sht.payout.description</code>.
     */
    public void setDescription(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>sht.payout.description</code>.
     */
    public String getDescription() {
        return (String) get(18);
    }

    /**
     * Setter for <code>sht.payout.account_legal_agreement_id</code>.
     */
    public void setAccountLegalAgreementId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>sht.payout.account_legal_agreement_id</code>.
     */
    public String getAccountLegalAgreementId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>sht.payout.account_legal_agreement_signed_at</code>.
     */
    public void setAccountLegalAgreementSignedAt(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>sht.payout.account_legal_agreement_signed_at</code>.
     */
    public LocalDateTime getAccountLegalAgreementSignedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>sht.payout.account_type</code>.
     */
    public void setAccountType(PayoutAccountType value) {
        set(21, value);
    }

    /**
     * Getter for <code>sht.payout.account_type</code>.
     */
    public PayoutAccountType getAccountType() {
        return (PayoutAccountType) get(21);
    }

    /**
     * Setter for <code>sht.payout.fee</code>.
     */
    public void setFee(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>sht.payout.fee</code>.
     */
    public Long getFee() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>sht.payout.bank_address</code>.
     */
    public void setBankAddress(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>sht.payout.bank_address</code>.
     */
    public String getBankAddress() {
        return (String) get(23);
    }

    /**
     * Setter for <code>sht.payout.bank_bic</code>.
     */
    public void setBankBic(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>sht.payout.bank_bic</code>.
     */
    public String getBankBic() {
        return (String) get(24);
    }

    /**
     * Setter for <code>sht.payout.bank_iban</code>.
     */
    public void setBankIban(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>sht.payout.bank_iban</code>.
     */
    public String getBankIban() {
        return (String) get(25);
    }

    /**
     * Setter for <code>sht.payout.account_legal_name</code>.
     */
    public void setAccountLegalName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>sht.payout.account_legal_name</code>.
     */
    public String getAccountLegalName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>sht.payout.account_trading_name</code>.
     */
    public void setAccountTradingName(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>sht.payout.account_trading_name</code>.
     */
    public String getAccountTradingName() {
        return (String) get(27);
    }

    /**
     * Setter for <code>sht.payout.account_registered_address</code>.
     */
    public void setAccountRegisteredAddress(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>sht.payout.account_registered_address</code>.
     */
    public String getAccountRegisteredAddress() {
        return (String) get(28);
    }

    /**
     * Setter for <code>sht.payout.account_actual_address</code>.
     */
    public void setAccountActualAddress(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>sht.payout.account_actual_address</code>.
     */
    public String getAccountActualAddress() {
        return (String) get(29);
    }

    /**
     * Setter for <code>sht.payout.account_registered_number</code>.
     */
    public void setAccountRegisteredNumber(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>sht.payout.account_registered_number</code>.
     */
    public String getAccountRegisteredNumber() {
        return (String) get(30);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayoutRecord
     */
    public PayoutRecord() {
        super(Payout.PAYOUT);
    }

    /**
     * Create a detached, initialised PayoutRecord
     */
    public PayoutRecord(Long id, String partyId, String shopId, LocalDateTime createdAt, LocalDateTime fromTime, LocalDateTime toTime, PayoutStatus status, PayoutType type, Long amount, Long shopAcc, Long shopPayoutAcc, String currencyCode, String bankAccount, String bankLocalCode, String bankName, String bankPostAccount, String inn, String purpose, String description, String accountLegalAgreementId, LocalDateTime accountLegalAgreementSignedAt, PayoutAccountType accountType, Long fee, String bankAddress, String bankBic, String bankIban, String accountLegalName, String accountTradingName, String accountRegisteredAddress, String accountActualAddress, String accountRegisteredNumber) {
        super(Payout.PAYOUT);

        set(0, id);
        set(1, partyId);
        set(2, shopId);
        set(3, createdAt);
        set(4, fromTime);
        set(5, toTime);
        set(6, status);
        set(7, type);
        set(8, amount);
        set(9, shopAcc);
        set(10, shopPayoutAcc);
        set(11, currencyCode);
        set(12, bankAccount);
        set(13, bankLocalCode);
        set(14, bankName);
        set(15, bankPostAccount);
        set(16, inn);
        set(17, purpose);
        set(18, description);
        set(19, accountLegalAgreementId);
        set(20, accountLegalAgreementSignedAt);
        set(21, accountType);
        set(22, fee);
        set(23, bankAddress);
        set(24, bankBic);
        set(25, bankIban);
        set(26, accountLegalName);
        set(27, accountTradingName);
        set(28, accountRegisteredAddress);
        set(29, accountActualAddress);
        set(30, accountRegisteredNumber);
    }
}
