/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.PayoutStatus;
import com.rbkmoney.payouter.domain.enums.PayoutType;
import com.rbkmoney.payouter.domain.tables.Payout;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PayoutRecord extends UpdatableRecordImpl<PayoutRecord> implements Record21<Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, PayoutStatus, PayoutType, Long, Long, Long, String, String, String, String, String, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = -31848176;

    /**
     * Setter for <code>sht.payout.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.payout.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.payout.party_id</code>.
     */
    public void setPartyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.payout.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sht.payout.shop_id</code>.
     */
    public void setShopId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.payout.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.payout.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.payout.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>sht.payout.from_time</code>.
     */
    public void setFromTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.payout.from_time</code>.
     */
    public LocalDateTime getFromTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sht.payout.to_time</code>.
     */
    public void setToTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.payout.to_time</code>.
     */
    public LocalDateTime getToTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sht.payout.status</code>.
     */
    public void setStatus(PayoutStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.payout.status</code>.
     */
    public PayoutStatus getStatus() {
        return (PayoutStatus) get(6);
    }

    /**
     * Setter for <code>sht.payout.payout_type</code>.
     */
    public void setPayoutType(PayoutType value) {
        set(7, value);
    }

    /**
     * Getter for <code>sht.payout.payout_type</code>.
     */
    public PayoutType getPayoutType() {
        return (PayoutType) get(7);
    }

    /**
     * Setter for <code>sht.payout.amount</code>.
     */
    public void setAmount(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>sht.payout.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>sht.payout.shop_acc</code>.
     */
    public void setShopAcc(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>sht.payout.shop_acc</code>.
     */
    public Long getShopAcc() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>sht.payout.shop_payout_acc</code>.
     */
    public void setShopPayoutAcc(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>sht.payout.shop_payout_acc</code>.
     */
    public Long getShopPayoutAcc() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>sht.payout.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sht.payout.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sht.payout.bank_account</code>.
     */
    public void setBankAccount(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sht.payout.bank_account</code>.
     */
    public String getBankAccount() {
        return (String) get(12);
    }

    /**
     * Setter for <code>sht.payout.bank_bik</code>.
     */
    public void setBankBik(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sht.payout.bank_bik</code>.
     */
    public String getBankBik() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sht.payout.bank_name</code>.
     */
    public void setBankName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>sht.payout.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>sht.payout.bank_post_account</code>.
     */
    public void setBankPostAccount(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sht.payout.bank_post_account</code>.
     */
    public String getBankPostAccount() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sht.payout.inn</code>.
     */
    public void setInn(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>sht.payout.inn</code>.
     */
    public String getInn() {
        return (String) get(16);
    }

    /**
     * Setter for <code>sht.payout.purpose</code>.
     */
    public void setPurpose(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>sht.payout.purpose</code>.
     */
    public String getPurpose() {
        return (String) get(17);
    }

    /**
     * Setter for <code>sht.payout.description</code>.
     */
    public void setDescription(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>sht.payout.description</code>.
     */
    public String getDescription() {
        return (String) get(18);
    }

    /**
     * Setter for <code>sht.payout.account_legal_agreement_id</code>.
     */
    public void setAccountLegalAgreementId(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>sht.payout.account_legal_agreement_id</code>.
     */
    public String getAccountLegalAgreementId() {
        return (String) get(19);
    }

    /**
     * Setter for <code>sht.payout.account_legal_agreement_signed_at</code>.
     */
    public void setAccountLegalAgreementSignedAt(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>sht.payout.account_legal_agreement_signed_at</code>.
     */
    public LocalDateTime getAccountLegalAgreementSignedAt() {
        return (LocalDateTime) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, PayoutStatus, PayoutType, Long, Long, Long, String, String, String, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, String, LocalDateTime, LocalDateTime, LocalDateTime, PayoutStatus, PayoutType, Long, Long, Long, String, String, String, String, String, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Payout.PAYOUT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Payout.PAYOUT.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Payout.PAYOUT.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return Payout.PAYOUT.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return Payout.PAYOUT.FROM_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return Payout.PAYOUT.TO_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<PayoutStatus> field7() {
        return Payout.PAYOUT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<PayoutType> field8() {
        return Payout.PAYOUT.PAYOUT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Payout.PAYOUT.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Payout.PAYOUT.SHOP_ACC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Payout.PAYOUT.SHOP_PAYOUT_ACC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Payout.PAYOUT.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Payout.PAYOUT.BANK_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Payout.PAYOUT.BANK_BIK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Payout.PAYOUT.BANK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Payout.PAYOUT.BANK_POST_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return Payout.PAYOUT.INN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Payout.PAYOUT.PURPOSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return Payout.PAYOUT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return Payout.PAYOUT.ACCOUNT_LEGAL_AGREEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field21() {
        return Payout.PAYOUT.ACCOUNT_LEGAL_AGREEMENT_SIGNED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getFromTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getToTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutStatus value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutType value8() {
        return getPayoutType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getShopAcc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getShopPayoutAcc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getBankAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getBankBik();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getBankName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getBankPostAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getPurpose();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getAccountLegalAgreementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value21() {
        return getAccountLegalAgreementSignedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value2(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value3(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value5(LocalDateTime value) {
        setFromTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value6(LocalDateTime value) {
        setToTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value7(PayoutStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value8(PayoutType value) {
        setPayoutType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value9(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value10(Long value) {
        setShopAcc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value11(Long value) {
        setShopPayoutAcc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value12(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value13(String value) {
        setBankAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value14(String value) {
        setBankBik(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value15(String value) {
        setBankName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value16(String value) {
        setBankPostAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value17(String value) {
        setInn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value18(String value) {
        setPurpose(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value19(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value20(String value) {
        setAccountLegalAgreementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord value21(LocalDateTime value) {
        setAccountLegalAgreementSignedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PayoutRecord values(Long value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, LocalDateTime value6, PayoutStatus value7, PayoutType value8, Long value9, Long value10, Long value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18, String value19, String value20, LocalDateTime value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PayoutRecord
     */
    public PayoutRecord() {
        super(Payout.PAYOUT);
    }

    /**
     * Create a detached, initialised PayoutRecord
     */
    public PayoutRecord(Long id, String partyId, String shopId, LocalDateTime createdAt, LocalDateTime fromTime, LocalDateTime toTime, PayoutStatus status, PayoutType payoutType, Long amount, Long shopAcc, Long shopPayoutAcc, String currencyCode, String bankAccount, String bankBik, String bankName, String bankPostAccount, String inn, String purpose, String description, String accountLegalAgreementId, LocalDateTime accountLegalAgreementSignedAt) {
        super(Payout.PAYOUT);

        set(0, id);
        set(1, partyId);
        set(2, shopId);
        set(3, createdAt);
        set(4, fromTime);
        set(5, toTime);
        set(6, status);
        set(7, payoutType);
        set(8, amount);
        set(9, shopAcc);
        set(10, shopPayoutAcc);
        set(11, currencyCode);
        set(12, bankAccount);
        set(13, bankBik);
        set(14, bankName);
        set(15, bankPostAccount);
        set(16, inn);
        set(17, purpose);
        set(18, description);
        set(19, accountLegalAgreementId);
        set(20, accountLegalAgreementSignedAt);
    }
}
