/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.enums.RefundStatus;
import com.rbkmoney.payouter.domain.tables.Refund;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RefundRecord extends UpdatableRecordImpl<RefundRecord> implements Record16<Long, Long, String, String, String, String, String, RefundStatus, LocalDateTime, String, Long, Long, Long, LocalDateTime, Long, String> {

    private static final long serialVersionUID = 490307992;

    /**
     * Setter for <code>sht.refund.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.refund.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sht.refund.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.refund.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>sht.refund.shop_id</code>.
     */
    public void setShopId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.refund.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sht.refund.party_id</code>.
     */
    public void setPartyId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sht.refund.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sht.refund.invoice_id</code>.
     */
    public void setInvoiceId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sht.refund.invoice_id</code>.
     */
    public String getInvoiceId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sht.refund.payment_id</code>.
     */
    public void setPaymentId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sht.refund.payment_id</code>.
     */
    public String getPaymentId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sht.refund.refund_id</code>.
     */
    public void setRefundId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sht.refund.refund_id</code>.
     */
    public String getRefundId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sht.refund.status</code>.
     */
    public void setStatus(RefundStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>sht.refund.status</code>.
     */
    public RefundStatus getStatus() {
        return (RefundStatus) get(7);
    }

    /**
     * Setter for <code>sht.refund.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sht.refund.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>sht.refund.reason</code>.
     */
    public void setReason(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sht.refund.reason</code>.
     */
    public String getReason() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sht.refund.amount</code>.
     */
    public void setAmount(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>sht.refund.amount</code>.
     */
    public Long getAmount() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>sht.refund.fee</code>.
     */
    public void setFee(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>sht.refund.fee</code>.
     */
    public Long getFee() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>sht.refund.payout_id</code>.
     */
    public void setPayoutId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>sht.refund.payout_id</code>.
     */
    public Long getPayoutId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>sht.refund.succeeded_at</code>.
     */
    public void setSucceededAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>sht.refund.succeeded_at</code>.
     */
    public LocalDateTime getSucceededAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>sht.refund.domain_revision</code>.
     */
    public void setDomainRevision(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>sht.refund.domain_revision</code>.
     */
    public Long getDomainRevision() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>sht.refund.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sht.refund.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, String, String, String, String, String, RefundStatus, LocalDateTime, String, Long, Long, Long, LocalDateTime, Long, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, Long, String, String, String, String, String, RefundStatus, LocalDateTime, String, Long, Long, Long, LocalDateTime, Long, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Refund.REFUND.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Refund.REFUND.EVENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Refund.REFUND.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Refund.REFUND.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Refund.REFUND.INVOICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Refund.REFUND.PAYMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Refund.REFUND.REFUND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<RefundStatus> field8() {
        return Refund.REFUND.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return Refund.REFUND.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Refund.REFUND.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Refund.REFUND.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Refund.REFUND.FEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Refund.REFUND.PAYOUT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return Refund.REFUND.SUCCEEDED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return Refund.REFUND.DOMAIN_REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Refund.REFUND.CURRENCY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getEventId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRefundId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundStatus value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getFee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getPayoutId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getSucceededAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getDomainRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value3(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value4(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value5(String value) {
        setInvoiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value6(String value) {
        setPaymentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value7(String value) {
        setRefundId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value8(RefundStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value10(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value11(Long value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value12(Long value) {
        setFee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value13(Long value) {
        setPayoutId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value14(LocalDateTime value) {
        setSucceededAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value15(Long value) {
        setDomainRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord value16(String value) {
        setCurrencyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RefundRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, RefundStatus value8, LocalDateTime value9, String value10, Long value11, Long value12, Long value13, LocalDateTime value14, Long value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RefundRecord
     */
    public RefundRecord() {
        super(Refund.REFUND);
    }

    /**
     * Create a detached, initialised RefundRecord
     */
    public RefundRecord(Long id, Long eventId, String shopId, String partyId, String invoiceId, String paymentId, String refundId, RefundStatus status, LocalDateTime createdAt, String reason, Long amount, Long fee, Long payoutId, LocalDateTime succeededAt, Long domainRevision, String currencyCode) {
        super(Refund.REFUND);

        set(0, id);
        set(1, eventId);
        set(2, shopId);
        set(3, partyId);
        set(4, invoiceId);
        set(5, paymentId);
        set(6, refundId);
        set(7, status);
        set(8, createdAt);
        set(9, reason);
        set(10, amount);
        set(11, fee);
        set(12, payoutId);
        set(13, succeededAt);
        set(14, domainRevision);
        set(15, currencyCode);
    }
}
