/*
 * This file is generated by jOOQ.
*/
package com.rbkmoney.payouter.domain.tables.records;


import com.rbkmoney.payouter.domain.tables.ShopMeta;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopMetaRecord extends UpdatableRecordImpl<ShopMetaRecord> implements Record3<String, String, LocalDateTime> {

    private static final long serialVersionUID = 2007498060;

    /**
     * Setter for <code>sht.shop_meta.party_id</code>.
     */
    public void setPartyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sht.shop_meta.party_id</code>.
     */
    public String getPartyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sht.shop_meta.shop_id</code>.
     */
    public void setShopId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sht.shop_meta.shop_id</code>.
     */
    public String getShopId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sht.shop_meta.wtime</code>.
     */
    public void setWtime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sht.shop_meta.wtime</code>.
     */
    public LocalDateTime getWtime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ShopMeta.SHOP_META.PARTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ShopMeta.SHOP_META.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field3() {
        return ShopMeta.SHOP_META.WTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getPartyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value3() {
        return getWtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopMetaRecord value1(String value) {
        setPartyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopMetaRecord value2(String value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopMetaRecord value3(LocalDateTime value) {
        setWtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShopMetaRecord values(String value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopMetaRecord
     */
    public ShopMetaRecord() {
        super(ShopMeta.SHOP_META);
    }

    /**
     * Create a detached, initialised ShopMetaRecord
     */
    public ShopMetaRecord(String partyId, String shopId, LocalDateTime wtime) {
        super(ShopMeta.SHOP_META);

        set(0, partyId);
        set(1, shopId);
        set(2, wtime);
    }
}
